"""Nomes dos bancos pelo código COMPE (3 dígitos), usados no resumo do arquivo quando o Header traz o
código do banco. Vale para todos os layouts (CNAB 400 e 240)."""

NOMES_DOS_BANCOS = {
    "001": "Banco do Brasil",
    "003": "Banco da Amazonia",
    "004": "Banco do Nordeste do Brasil",
    "021": "Banestes",
    "025": "Banco Alfa",
    "033": "Santander",
    "037": "Banpara",
    "041": "Banrisul",
    "047": "Banese",
    "070": "BRB - Banco de Brasilia",
    "077": "Banco Inter",
    "084": "Uniprime Norte do Parana",
    "085": "Ailos (Cooperativa Central de Crédito)",
    "104": "Caixa Economica Federal",
    "121": "Banco Agibank",
    "136": "Unicred do Brasil",
    "151": "Banco Nossa Caixa (incorporado ao Banco do Brasil)",
    "175": "Banco Rabobank",
    "212": "Banco Original",
    "224": "Banco Fibra",
    "237": "Bradesco",
    "246": "Banco ABC Brasil",
    "260": "Nu Pagamentos (Nubank)",
    "290": "PagSeguro Internet (PagBank)",
    "318": "Banco BMG",
    "336": "Banco C6 (C6 Bank)",
    "341": "Itau Unibanco",
    "348": "Banco XP",
    "356": "Banco Real (incorporado ao Santander)",
    "380": "PicPay",
    "399": "HSBC Bank Brasil",
    "403": "Cora Sociedade de Crédito Direto",
    "422": "Banco Safra",
    "456": "Banco MUFG Brasil",
    "604": "Banco Industrial do Brasil",
    "623": "Banco Pan (ex-Panamericano)",
    "633": "Banco Rendimento",
    "655": "Banco Votorantim (BV)",
    "707": "Banco Daycoval",
    "745": "Banco Citibank",
    "748": "Sicredi",
    "756": "Sicoob (Bancoob)",
}
