"""
CNAB 400 Santander (banco 033; o Header também aceita 353, código legado) - Cobrança - referência de campos.

Fonte: "Layout Cobrança H7800 - CNAB 353/400 posições - padrão Santander", versão 2.37, fevereiro/2026
(manual oficial do Banco Santander, https://www.santander.com.br/layout-de-arquivos). As notas citadas
nas descrições são as notas desse manual.

Registros (posição 1 da linha):
  Remessa: 0 Header; 1 Movimento; 8 Tipo de pagamento e dados de QR Code/PIX (opcional, Boleto SX);
           2 Mensagem no Recibo do Pagador e 4/5/6/7 Mensagem na Ficha de Compensação (opcionais); 9 Trailer.
  Retorno: 0 Header; 1 Movimento; 2 Dados de QR Code/PIX (opcional); 9 Trailer.

Convenções de nome (a interface depende delas): o resumo da grade procura por trechos como "Data de
Vencimento", "Valor Nominal", "Nosso Número", "Número do Documento", "Código de Movimento" e "Nome do
Pagador"; "Valor Pago" é o valor liquidado no retorno; campos reservados levam "Uso Reservado (Filler)" e
aparecem acinzentados. Por isso alguns títulos trazem, entre parênteses, o nome que o manual usa.

Inconsistências do próprio manual, mantidas como estão até conferir com arquivo real: no registro 8 os
percentuais (020-024 e 038-042) ocupam 5 posições mas declaram tamanho 3; no Movimento de retorno o
"Complemento" (384-385) declara tamanho 1 para 2 posições. Os tamanhos aqui seguem as posições.
"""

# --- Remessa ----------------------------------------------------------------------------------

# Header Remessa
HEADER_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Tipo do registro: '0' identifica o Header, a primeira linha do arquivo."),
    ("Código da Remessa", 2, 2,
     "'1' = arquivo de remessa, enviado pelo Beneficiário ao banco (no retorno o banco usa '2')."),
    ("Literal de Transmissão", 3, 9,
     "Texto fixo 'REMESSA', que confirma o sentido do arquivo."),
    ("Código do Tipo Serviço", 10, 11,
     "Código do serviço: '01' = Cobrança."),
    ("Literal de Serviço", 12, 26,
     "Texto fixo 'COBRANCA', o nome do serviço do código anterior."),
    ("Código de Transmissão", 27, 46,
     "Código de transmissão: informação cedida pelo Santander que identifica o arquivo remessa do cliente (nota 1). Com agência e contas novas, de 10 posições, o manual compõe este trecho com a agência sem dígito (27-30) e as 8 primeiras posições da conta movimento (31-38) e da conta cobrança (39-46) (nota 2)."),
    ("Nome do Beneficiário", 47, 76,
     "Nome da empresa beneficiária: quem emite os boletos e recebe os pagamentos."),
    ("Código do Banco", 77, 79,
     "Código do Santander na compensação: '033' (o manual também aceita '353', código legado)."),
    ("Nome do Banco", 80, 94,
     "Texto fixo 'SANTANDER', o nome do banco."),
    ("Data da Geração do Arquivo", 95, 100,
     "Data em que o arquivo foi gerado, no formato DDMMAA."),
    ("Uso Reservado (Filler)", 101, 116,
     "Reservado para uso do Banco (16 posições); preenchido com zeros."),
    ("Mensagem 1", 117, 163,
     "Mensagem 1 do Header: texto livre de 47 posições, informado uma vez para o arquivo. O manual não detalha onde é impressa; as mensagens de cada boleto vão nos registros opcionais 2 (Recibo do Pagador) e 4 a 7 (Ficha de Compensação). A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Mensagem 2", 164, 210,
     "Mensagem 2 do Header: texto livre de 47 posições, informado uma vez para o arquivo. O manual não detalha onde é impressa; as mensagens de cada boleto vão nos registros opcionais 2 (Recibo do Pagador) e 4 a 7 (Ficha de Compensação). A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Mensagem 3", 211, 257,
     "Mensagem 3 do Header: texto livre de 47 posições, informado uma vez para o arquivo. O manual não detalha onde é impressa; as mensagens de cada boleto vão nos registros opcionais 2 (Recibo do Pagador) e 4 a 7 (Ficha de Compensação). A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Mensagem 4", 258, 304,
     "Mensagem 4 do Header: texto livre de 47 posições, informado uma vez para o arquivo. O manual não detalha onde é impressa; as mensagens de cada boleto vão nos registros opcionais 2 (Recibo do Pagador) e 4 a 7 (Ficha de Compensação). A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Mensagem 5", 305, 351,
     "Mensagem 5 do Header: texto livre de 47 posições, informado uma vez para o arquivo. O manual não detalha onde é impressa; as mensagens de cada boleto vão nos registros opcionais 2 (Recibo do Pagador) e 4 a 7 (Ficha de Compensação). A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Uso Reservado (Filler)", 352, 385,
     "Reservado para uso do Banco (34 posições); preenchido com brancos."),
    ("Uso Reservado (Filler)", 386, 391,
     "Reservado para uso do Banco (6 posições); preenchido com brancos."),
    ("Nº sequencial do arquivo", 392, 394,
     "Número da versão (sequência) da remessa, opcional. Se informado, o banco o controla e gera um número sequencial para cada remessa (nota 32)."),
    ("Nº sequencial do registro no arquivo", 395, 400,
     "Número da linha no arquivo: no Header é sempre '000001'."),
]

# Detail Remessa
DETAIL_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Tipo do registro: '1' identifica o Registro de Movimento, uma linha por boleto (entrada ou instrução sobre um boleto já registrado)."),
    ("Tipo de inscrição do beneficiário", 2, 3,
     "Tipo do documento do Beneficiário nas posições 4-17: '01' = CPF, '02' = CNPJ."),
    ("Inscrição do beneficiário", 4, 17,
     "CPF ou CNPJ do Beneficiário, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 38)."),
    ("Código da agência beneficiário", 18, 21,
     "Agência do Beneficiário no Santander, 4 posições. Na agência nova, sem o dígito; na velha, com ou sem o dígito, conforme o cadastro (nota 2)."),
    ("Conta movimento beneficiário", 22, 29,
     "Conta corrente (conta movimento) do Beneficiário, 8 posições. Com a conta nova, de 10 posições (9 + dígito), vão aqui as 8 primeiras (nota 2)."),
    ("Conta cobrança beneficiário", 30, 37,
     "Conta cobrança do Beneficiário, 8 posições. Com a conta nova, de 10 posições (CCCCCCCCC-D), vão aqui as 8 primeiras; a última posição e o dígito vão no Complemento (384-385), com 'I' no Identificador do complemento (383). Exemplo do manual: conta 001234567-8 = '00123456' aqui e '78' no Complemento (nota 2)."),
    ("Identificação do boleto na empresa", 38, 62,
     "Número de controle do participante, opcional: identificação livre do boleto no sistema do Beneficiário. Se informado, volta no retorno quando o boleto é liquidado, para o Beneficiário identificar o Pagador (nota 19)."),
    ("Nosso Número (Identificação do boleto no banco)", 63, 70,
     "Nosso Número: número do boleto no banco. Se vier zerado, o Santander atribui automaticamente. Na Cobrança Rápida com Registro (o Beneficiário emite o boleto) é obrigatório informá-lo, com o dígito de controle calculado pela regra do manual (nota 3). Com IOF cobrado \"na tabela\", as 2 primeiras posições trazem o código da alíquota (nota 5)."),
    ("Data do desconto 2", 71, 76,
     "Data limite do segundo desconto (DDMMAA); o valor do segundo desconto vai em 206-218. Deve ser maior que a data de emissão, menor ou igual ao vencimento e diferente da data do primeiro desconto (nota 11)."),
    ("Uso Reservado (Filler)", 77, 77,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Código de Multa", 78, 78,
     "Código da multa: o manual manda preencher sempre com '4', com o percentual obrigatório em 79-82. Neste layout o banco não aplica a multa cadastrada no perfil do Beneficiário (nota 4)."),
    ("Percentual de Multa", 79, 82,
     "Percentual da multa por atraso, com 2 casas decimais sem vírgula: '0200' = 2,00% (nota 4)."),
    ("Código da Moeda", 83, 84,
     "Código da moeda: o manual pede '00'. Código inválido volta com o erro 513 (Código de Moeda Inválido)."),
    ("Valor do boleto em outra unidade", 85, 97,
     "Valor do boleto em outra unidade de valor (5 casas decimais). O manual indica que não se aplica."),
    ("Uso Reservado (Filler)", 98, 101,
     "Reservado para uso do Banco (4 posições); preenchido com brancos."),
    ("Data da Multa", 102, 107,
     "Data a partir da qual a multa é cobrada (DDMMAA). Com zeros, a multa vale logo após o vencimento; se informada, deve ser maior que a data de vencimento (nota 4)."),
    ("Tipo de Cobrança (Código da Carteira)", 108, 108,
     "Carteira do boleto: '1' Cobrança Simples (Eletrônica com Registro), '3' Caucionada (Eletrônica com Registro), '5' Simples (Rápida com Registro), '6' Caucionada (Rápida com Registro), '7' Descontada (Eletrônica com Registro), '8' Cessão (Eletrônica com Registro, só com o produto SX Integra contratado) (nota 20)."),
    ("Código de Movimento Remessa (Código da Ocorrência)", 109, 110,
     "Instrução que o Beneficiário comanda para o boleto. '01' registra o boleto (entrada); os demais agem sobre um boleto já registrado: '02' baixa, '04'/'05' conceder ou cancelar abatimento, '06' alterar vencimento, '07' e '08' alterar o número de controle e o Seu Número, '09' protestar, '18' sustar o protesto e '47' a '49' alterar o valor nominal, o mínimo ou o máximo. '15' a '17' são da carteira de Cessão (produto SX Integra). Tabela completa em COMANDO_REMESSA_CODES (nota 21)."),
    ("Número do Documento (Seu Número)", 111, 120,
     "Seu Número: número adotado e controlado pelo Beneficiário para identificar o documento cobrado (número da duplicata, da apólice etc.). Volta no retorno e é essencial para boletos que vão a protesto (nota 22)."),
    ("Data de vencimento do boleto", 121, 126,
     "Data de vencimento do boleto (DDMMAA). Deve ser válida, posterior à data de entrada do boleto e no máximo 10 anos depois dela; '111111' ou '999999' é rejeitado. Não se pode usar 'Contra Apresentação' nem 'À vista' (nota 7)."),
    ("Valor nominal do boleto", 127, 139,
     "Valor nominal do boleto, com 2 casas decimais sem vírgula. Só as espécies BDP (08) e BCC (19) aceitam valor zerado e alteração do valor nominal (nota 10)."),
    ("Número do banco cobrador", 140, 142,
     "Código do Santander na compensação: '033' (o manual também aceita '353', código legado)."),
    ("Código agência Cobradora", 143, 147,
     "Agência cobradora do Santander: informar só na carteira '5' (Cobrança Simples Rápida com Registro); nas demais, zeros (nota 23)."),
    ("Espécie do boleto", 148, 149,
     "Espécie (tipo de documento) do boleto: '01' DM Duplicata Mercantil, '02' NP Nota Promissória, '03' AP Apólice de Seguro, '05' RC Recibo, '06' DS Duplicata de Serviço, '07' LC Letra de Câmbio, '08' BDP Boleto de Proposta, '19' BCC Boleto de Cartão de Crédito, '33' BDA Boleto de Depósito e Aporte (ver ESPECIE_BOLETO_CODES). BDP e BCC não admitem juros, multa nem protesto; o BDA tem regras próprias de pagamento (notas 6, 8, 24 e 33)."),
    ("Identificação boleto aceite / não aceite", 150, 150,
     "Aceite do boleto: 'N' = não aceite, o único conteúdo previsto no manual."),
    ("Data de emissão do boleto", 151, 156,
     "Data de emissão do boleto (DDMMAA); deve ser anterior à data de vencimento (nota 9)."),
    ("Primeira instrução", 157, 158,
     "Primeira instrução de cobrança: '00' Não há instruções (vale o que estiver no perfil do Beneficiário); '02' Baixar após 15 dias do vencimento; '03' Baixar após 30 dias do vencimento; '04' Não baixar; '06' Protestar (dias em 392-393); '07' Não protestar; '08' Não cobrar juros de mora (ver INSTRUCAO_CODES). Com protesto ou baixa ligados no perfil do Beneficiário, '00' segue o perfil; para não protestar ou não baixar este boleto, mande '07' ou '04' (notas 13 e 25)."),
    ("Segunda instrução", 159, 160,
     "Segunda instrução de cobrança, com os mesmos códigos da primeira: '00' Não há instruções (vale o que estiver no perfil do Beneficiário); '02' Baixar após 15 dias do vencimento; '03' Baixar após 30 dias do vencimento; '04' Não baixar; '06' Protestar (dias em 392-393); '07' Não protestar; '08' Não cobrar juros de mora (ver INSTRUCAO_CODES). Com '06' em qualquer das duas, informe os dias para protesto em 392-393 (notas 25 e 28)."),
    ("Valor de Mora dia", 161, 173,
     "Valor dos juros de mora por dia de atraso, com 2 casas decimais sem vírgula."),
    ("Data Limite para concessão do desconto", 174, 179,
     "Data limite para conceder o desconto (DDMMAA): maior que a data de emissão e menor ou igual ao vencimento (nota 11)."),
    ("Valor do desconto a ser concedido", 180, 192,
     "Valor do desconto concedido se o pagamento ocorrer até a data limite (174-179), com 2 casas decimais. Não pode ser maior ou igual ao valor nominal (nota 11)."),
    ("Percentual do IOF a ser recolhido", 193, 205,
     "Percentual do IOF a recolher, com 5 casas decimais sem vírgula. A cobrança do IOF segue o cadastro do convênio: 0 não cobra; 1 cobra na barra ou no cadastro (sem alíquota no arquivo, vale a do perfil); 2 cobra no cadastro; 3 cobra na tabela, com o código da alíquota nas 2 primeiras posições do Nosso Número (nota 5)."),
    ("Valor do abatimento ou Valor do segundo desconto", 206, 218,
     "Valor do abatimento ou do segundo desconto (cuja data vai em 71-76), com 2 casas decimais. Não pode ser maior ou igual ao valor nominal, e a soma de desconto e abatimento também não (notas 11 e 12)."),
    ("Tipo de inscrição do Pagador", 219, 220,
     "Tipo do documento do Pagador: '01' = CPF, '02' = CNPJ. O documento é obrigatório e tem o dígito conferido: ausente ou inválido, a entrada é rejeitada. Não pode ser igual ao do Beneficiário (nem a raiz do CNPJ), a não ser na espécie 33, BDA (nota 26)."),
    ("Inscrição do Pagador", 221, 234,
     "CPF ou CNPJ do Pagador, alinhado à direita e completado com zeros à esquerda; aceita o CNPJ alfanumérico (notas 26 e 38)."),
    ("Nome do Pagador", 235, 274,
     "Nome de quem vai pagar o boleto. Obrigatório: sem ele volta o erro 101 (Nome do Pagador não informado)."),
    ("Endereço do Pagador", 275, 314,
     "Endereço do Pagador (logradouro, número e complemento). Obrigatório (nota 27)."),
    ("Bairro do Pagador", 315, 326,
     "Bairro do Pagador. Obrigatório: sem ele volta o erro 160 (nota 27)."),
    ("Cep do Pagador", 327, 331,
     "Cinco primeiros dígitos do CEP do Pagador. Obrigatório; CEP não encontrado volta com o erro 124 (nota 27)."),
    ("Sufixo do Cep do Pagador", 332, 334,
     "Três últimos dígitos (sufixo) do CEP do Pagador (nota 27)."),
    ("Cidade do Pagador", 335, 349,
     "Cidade do Pagador. Obrigatória (nota 27)."),
    ("Unidade de Federação do Pagador", 350, 351,
     "Sigla da Unidade da Federação do Pagador. Obrigatória, e precisa existir e ser válida (nota 27)."),
    ("Uso Reservado (Filler)", 352, 381,
     "Reservado para uso do Banco (30 posições); preenchido com brancos."),
    ("Uso Reservado (Filler)", 382, 382,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Identificador do complemento", 383, 383,
     "'I' quando a conta cobrança é nova, de 10 posições: avisa que a última posição e o dígito da conta estão no Complemento (384-385). Com a conta velha, brancos (nota 2)."),
    ("Complemento", 384, 385,
     "Última posição da conta cobrança nova e o dígito (conta 001234567-8 = '78'), usado junto com 'I' na posição 383. Com a conta velha, brancos (nota 2)."),
    ("Uso Reservado (Filler)", 386, 391,
     "Reservado para uso do Banco (6 posições); preenchido com brancos."),
    ("Número de dias corridos para Protesto", 392, 393,
     "Quantidade de dias corridos para protesto. Informar quando a primeira ou a segunda instrução (157-160) for '06', Protestar (nota 28)."),
    ("Uso Reservado (Filler)", 394, 394,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Número sequencial do registro no arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# Qrcode Remessa
QRCODE_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Tipo do registro: '8' identifica o registro opcional de tipo de pagamento e dados do QR Code Pix (Boleto SX). Vai logo após o registro 1 de entrada do boleto (movimento '01'); com outro movimento, os dados do QR Code são desconsiderados. Só vale para a Cobrança Simples Rápida com Registro, com o boleto impresso pelo Beneficiário."),
    ("Identificação do tipo de pagamento", 2, 3,
     "Tipo de pagamento aceito: '00' conforme o perfil do Beneficiário; '01' aceita qualquer valor; '02' entre o mínimo e o máximo; '03' não aceita pagamento com valor divergente. Pelo QR Code o pagamento é sempre pelo valor nominal, sem alteração; estas regras valem para o pagamento pelo código de barras (nota 16)."),
    ("Quantidade de pagamento possíveis", 4, 5,
     "Quantidade de pagamentos que o boleto aceita: de 01 a 99 (nota 17)."),
    ("Tipo de valor informado", 6, 6,
     "Como ler os limites deste registro: '1' = percentual, '2' = valor (nota 18)."),
    ("Valor Máximo", 7, 19,
     "Valor máximo aceito no pagamento, com 2 casas decimais sem vírgula, usado quando o tipo de valor (posição 6) é '2'."),
    ("% (Percentual) Máximo", 20, 24,
     "Percentual máximo aceito no pagamento, com 2 casas decimais sem vírgula, usado quando o tipo de valor (posição 6) é '1'. O manual declara tamanho 3 para estas 5 posições; aqui vale a posição."),
    ("Valor Mínimo", 25, 37,
     "Valor mínimo aceito no pagamento, com 2 casas decimais sem vírgula, usado quando o tipo de valor (posição 6) é '2'."),
    ("% (Percentual) Mínimo", 38, 42,
     "Percentual mínimo aceito no pagamento, com 2 casas decimais sem vírgula, usado quando o tipo de valor (posição 6) é '1'. O manual declara tamanho 3 para estas 5 posições; aqui vale a posição."),
    ("Tipo de Chave DICT", 43, 43,
     "Tipo da chave Pix que o Beneficiário cadastrou no Santander: '1' CPF, '2' CNPJ, '3' celular, '4' e-mail, '5' EVP (chave aleatória) (nota 34)."),
    ("Código Chave DICT", 44, 120,
     "Chave Pix cadastrada no banco, que identifica o Beneficiário e a conta que recebe os créditos. Sem uma chave válida para receber Pix não há QR Code (nota 35)."),
    ("Código de identificação do Qr Code (TXID)", 121, 155,
     "Identificador do QR Code (TXID), opcional: único por boleto, de 26 a 35 caracteres, só letras e números, sem brancos. Com menos de 26, o boleto é registrado sem QR Code (ocorrência 509); repetido na mesma remessa, só um boleto leva o QR Code, e em remessas diferentes o boleto é rejeitado. Em branco, o banco gera o TXID (nota 37)."),
    ("Uso Reservado (Filler)", 156, 394,
     "Reservado para uso do Banco (239 posições); preenchido com brancos."),
    ("Número sequencial do registro do arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# Mensagem Remessa
MENSAGEM_REMESSA_FIELDS = [
    ("Código do registro", 1, 1,
     "Tipo do registro de mensagem: '2' = mensagem no Recibo do Pagador (até 3 mensagens por linha e até 24 linhas por boleto; as 2ª vias dos canais Santander mostram até 7 linhas); '4', '5', '6' e '7' = mensagens na Ficha de Compensação, uma linha de cada, que não aparecem nas 2ª vias."),
    ("Uso Reservado (Filler)", 2, 17,
     "Reservado para uso do Banco (16 posições)."),
    ("Código da Agência do Beneficiário", 18, 21,
     "Agência do Beneficiário no Santander, 4 posições. Na agência nova, sem o dígito; na velha, com ou sem o dígito, conforme o cadastro (nota 2)."),
    ("Conta Movimento Beneficiário", 22, 29,
     "Conta corrente (conta movimento) do Beneficiário, 8 posições. Com a conta nova, de 10 posições (9 + dígito), vão aqui as 8 primeiras (nota 2)."),
    ("Conta Cobrança Beneficiário", 30, 37,
     "Conta cobrança do Beneficiário, 8 posições. Com a conta nova, de 10 posições, vão aqui as 8 primeiras; a última posição e o dígito vão no Complemento (384-385), com 'I' em 383 (nota 2)."),
    ("Uso Reservado (Filler)", 38, 47,
     "Reservado para uso do Banco (10 posições)."),
    ("Sub-sequência do registro (1ª mensagem)", 48, 49,
     "Número da primeira mensagem desta linha. O manual indica '01'."),
    ("Mensagem variável por boleto (1ª linha)", 50, 99,
     "Primeira mensagem variável deste boleto, com até 50 caracteres. A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Sub-sequência do registro (2ª mensagem)", 100, 101,
     "Número da segunda mensagem desta linha. O manual indica '02'."),
    ("Mensagem variável por boleto (2ª linha)", 102, 151,
     "Segunda mensagem variável deste boleto, com até 50 caracteres. A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Sub-sequência do registro (3ª mensagem)", 152, 153,
     "Número da terceira mensagem desta linha. O manual indica '02', o mesmo da segunda."),
    ("Mensagem variável por boleto (3ª linha)", 154, 203,
     "Terceira mensagem variável deste boleto, com até 50 caracteres. A FEBRABAN recomenda não usar as expressões \"taxa bancária\" e \"tarifa bancária\" em mensagens de cobrança."),
    ("Uso Reservado (Filler)", 204, 382,
     "Reservado para uso do Banco (179 posições; o manual declara 178 para as posições 204-382)."),
    ("Identificador do complemento", 383, 383,
     "'I' quando a conta cobrança é nova, de 10 posições: a última posição e o dígito da conta estão no Complemento (384-385). Com a conta velha, brancos (nota 2)."),
    ("Complemento", 384, 385,
     "Última posição da conta cobrança nova e o dígito (conta 001234567-8 = '78'), junto com 'I' na posição 383. Com a conta velha, brancos (nota 2)."),
    ("Uso Reservado (Filler)", 386, 394,
     "Reservado para uso do Banco (9 posições); preenchido com brancos."),
    ("Número sequencial do registro no arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# Trailer Remessa
TRAILER_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Tipo do registro: '9' identifica o Trailer, a última linha do arquivo."),
    ("Quantidade de registro no arquivo", 2, 7,
     "Quantidade de registros (linhas) do arquivo."),
    ("Valor Total dos boletos", 8, 20,
     "Valor total dos boletos do arquivo, com 2 casas decimais sem vírgula."),
    ("Uso Reservado (Filler)", 21, 394,
     "Reservado para uso do Banco (374 posições); preenchido com zeros."),
    ("Número sequencial de registro no arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# --- Retorno ----------------------------------------------------------------------------------

# Header Retorno
HEADER_RETORNO_FIELDS = [
    ("Código do registro", 1, 1,
     "Tipo do registro: '0' identifica o Header, a primeira linha do arquivo."),
    ("Código da remessa", 2, 2,
     "'2' = arquivo de retorno, enviado pelo banco ao Beneficiário (na remessa é '1')."),
    ("Literal de transmissão", 3, 9,
     "Texto fixo 'RETORNO', que confirma o sentido do arquivo."),
    ("Código de serviço", 10, 11,
     "Código do serviço: '01' = Cobrança."),
    ("Literal do serviço", 12, 26,
     "Texto fixo 'COBRANCA', o nome do serviço do código anterior."),
    ("Código da agência do beneficiário", 27, 30,
     "Agência do Beneficiário no Santander, 4 posições. Na agência nova, sem o dígito; na velha, com ou sem o dígito, conforme o cadastro (nota 2)."),
    ("Conta Movimento do beneficiário", 31, 38,
     "Conta corrente (conta movimento) do Beneficiário, 8 posições. Com a conta nova, de 10 posições (9 + dígito), vão aqui as 8 primeiras (nota 2)."),
    ("Conta Cobrança do beneficiário", 39, 46,
     "Conta cobrança do Beneficiário, 8 posições. Com a conta nova, de 10 posições (CCCCCCCCC-D), vêm aqui as 8 primeiras (nota 2)."),
    ("Nome do beneficiário", 47, 76,
     "Nome da empresa beneficiária."),
    ("Código do banco", 77, 79,
     "Código do Santander na compensação: '033' (o manual também aceita '353', código legado)."),
    ("Nome do banco", 80, 94,
     "Texto fixo 'SANTANDER', o nome do banco."),
    ("Data da geração do arquivo", 95, 100,
     "Data em que o banco gerou o arquivo de retorno, no formato DDMMAA."),
    ("Uso Reservado (Filler)", 101, 108,
     "Reservado para uso do Banco (8 posições); preenchido com zeros."),
    ("Código do beneficiário", 109, 117,
     "Código do Beneficiário no Santander."),
    ("Uso Reservado (Filler)", 118, 385,
     "Reservado para uso do Banco (268 posições); preenchido com brancos."),
    ("Sigla da empresa no sistema", 386, 389,
     "Sigla da empresa no sistema do banco."),
    ("Uso Reservado (Filler)", 390, 391,
     "Reservado para uso do Banco (2 posições); preenchido com brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Número sequencial do arquivo, controlado pelo banco quando o Beneficiário numera as remessas (nota 32)."),
    ("Número Sequencial do registro no arquivo", 395, 400,
     "Número da linha no arquivo: no Header é '000001'."),
]

# Detail Retorno
DETAIL_RETORNO_FIELDS = [
    ("Código do Registro", 1, 1,
     "Tipo do registro: '1' identifica o Registro de Movimento, uma linha por evento ocorrido com um boleto."),
    ("Tipo de inscrição do beneficiário", 2, 3,
     "Tipo do documento do Beneficiário nas posições 4-17: '01' = CPF, '02' = CNPJ."),
    ("Inscrição do beneficiário", 4, 17,
     "CPF ou CNPJ do Beneficiário, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 38)."),
    ("Código de agência do beneficiário", 18, 21,
     "Agência do Beneficiário no Santander, 4 posições. Na agência nova, sem o dígito; na velha, com ou sem o dígito, conforme o cadastro (nota 2)."),
    ("Conta movimento do beneficiário", 22, 29,
     "Conta corrente (conta movimento) do Beneficiário, 8 posições. Com a conta nova, de 10 posições (9 + dígito), vão aqui as 8 primeiras (nota 2)."),
    ("Conta cobrança do beneficiário", 30, 37,
     "Conta cobrança do Beneficiário, 8 posições. Com a conta nova, de 10 posições (CCCCCCCCC-D), vêm aqui as 8 primeiras; a última posição e o dígito vêm no Complemento (384-385), com 'I' no Identificador do complemento (338) (nota 2)."),
    ("Identificação do boleto na empresa cliente", 38, 62,
     "Número de controle do participante que o Beneficiário mandou na remessa, devolvido para ele identificar o boleto e o Pagador (nota 19)."),
    ("Nosso Número (Identificação do boleto no banco)", 63, 70,
     "Nosso Número: número do boleto no Santander."),
    ("Uso Reservado (Filler)", 71, 107,
     "Reservado para uso do Banco (37 posições); preenchido com brancos."),
    ("Tipo de Cobrança (Código da Carteira)", 108, 108,
     "Carteira do boleto: '2' Cobrança Simples (Eletrônica com Registro), '3' Caucionada (Eletrônica com Registro), '5' Simples (Rápida com Registro), '7' Descontada (Eletrônica com Registro), '8' Cessão (Eletrônica com Registro, só com o produto SX Integra). Atenção: no retorno a Simples Eletrônica vem como '2'; na remessa ela é '1' (nota 20)."),
    ("Código de Movimento de Retorno", 109, 110,
     "Evento que gerou esta linha do retorno: '02' entrada confirmada; '03' entrada ou instrução rejeitada (motivos em 137-145); '06' liquidação; '09' e '10' baixa; '12' e '13' abatimento; '14' alteração de vencimento; '15' a '27' cartório e protesto; '93' pagamento recebido (só o valor pago, sem desconto, juros e demais valores: a liquidação vale pelo retorno noturno) e '94' cancelamento desse pagamento. Boleto pago pelo QR Code Pix volta, por padrão, como '09' Baixa; se o banco parametrizar, como '09' com ocorrência 510 ou '06' com 511. Tabela completa em OCORRENCIA_CODES (notas 14, 15 e 29)."),
    ("Data da ocorrência", 111, 116,
     "Data em que o evento aconteceu (DDMMAA)."),
    ("Número do Documento (Seu Número)", 117, 126,
     "Seu Número informado na remessa, devolvido no retorno (nota 22)."),
    ("Nosso Número (Identificação do boleto no banco)", 127, 134,
     "Repete o Nosso Número, a identificação do boleto no banco."),
    ("Código Original da remessa", 135, 136,
     "Resultado do processamento da remessa: '00' sem erros; '01' entrada rejeitada; '02' evento rejeitado (diferente de entrada); '03' liquidação parcial; '95' baixa ou liquidação de Bolepix. Diferente de zero quando houve erro (nota 30)."),
    ("Código de Erro/Ocorrência (1ª ocorrência)", 137, 139,
     "Primeiro motivo de erro ou ocorrência, com 3 posições; brancos quando não há erro. Traz desde críticas da remessa (016 data de vencimento inválida, 092 Nosso Número já cadastrado...) até avisos do Pix (508 registrado com QR Code, 509 registrado sem QR Code, 510 baixado por Pix, 511 liquidado por Pix). Tabela em ERRO_OCORRENCIA_CODES (nota 31)."),
    ("Código de Erro/Ocorrência (2ª ocorrência)", 140, 142,
     "Segundo motivo de erro ou ocorrência, com os códigos de ERRO_OCORRENCIA_CODES; brancos quando não há (nota 31)."),
    ("Código de Erro/Ocorrência (3ª ocorrência)", 143, 145,
     "Terceiro motivo de erro ou ocorrência, com os códigos de ERRO_OCORRENCIA_CODES; brancos quando não há (nota 31)."),
    ("Uso Reservado (Filler)", 146, 146,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Data de vencimento do boleto", 147, 152,
     "Data de vencimento registrada para o boleto (DDMMAA)."),
    ("Valor nominal do boleto", 153, 165,
     "Valor nominal registrado para o boleto, com 2 casas decimais sem vírgula."),
    ("Número do banco cobrador", 166, 168,
     "Código do banco cobrador do boleto."),
    ("Código da agência recebedora do boleto", 169, 173,
     "Agência que recebeu o pagamento do boleto."),
    ("Espécie do boleto", 174, 175,
     "Espécie (tipo de documento) do boleto: '01' DM Duplicata Mercantil, '02' NP Nota Promissória, '03' AP Apólice de Seguro, '05' RC Recibo, '06' DS Duplicata de Serviço, '07' LC Letra de Câmbio, '08' BDP Boleto de Proposta, '19' BCC Boleto de Cartão de Crédito, '33' BDA Boleto de Depósito e Aporte (ver ESPECIE_BOLETO_CODES). (nota 24)"),
    ("Valor da tarifa cobrada", 176, 188,
     "Valor da tarifa cobrada pelo banco neste evento, com 2 casas decimais sem vírgula."),
    ("Valor de outras despesas", 189, 201,
     "Valor de outras despesas, com 2 casas decimais sem vírgula."),
    ("Valor de juros de atraso", 202, 214,
     "Valor de juros de atraso, com 2 casas decimais sem vírgula. O manual também traz o \"Valor do juros de mora\" (267-279), sem explicar a diferença entre os dois."),
    ("Valor de IOF recolhido", 215, 227,
     "Valor do IOF recolhido, com 2 casas decimais sem vírgula."),
    ("Valor do abatimento concedido", 228, 240,
     "Valor do abatimento concedido, com 2 casas decimais sem vírgula. Na liquidação de um boleto com desconto e abatimento, os dois valores concedidos vêm somados aqui (nota 12)."),
    ("Valor do desconto concedido", 241, 253,
     "Valor do desconto concedido, com 2 casas decimais sem vírgula. Na liquidação, o desconto vem somado ao abatimento em 228-240 (nota 12)."),
    ("Valor Pago (Valor total recebido)", 254, 266,
     "Valor total recebido do Pagador, com 2 casas decimais sem vírgula."),
    ("Valor do juros de mora", 267, 279,
     "Valor dos juros de mora, com 2 casas decimais sem vírgula (veja também \"Valor de juros de atraso\", 202-214)."),
    ("Valor de outros créditos", 280, 292,
     "Valor de outros créditos, com 2 casas decimais sem vírgula."),
    ("Uso Reservado (Filler)", 293, 293,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Identificação boleto aceite / não aceite", 294, 294,
     "Aceite do boleto: 'N' = não aceite, o único conteúdo previsto no manual."),
    ("Uso Reservado (Filler)", 295, 295,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Data da efetivação crédito", 296, 301,
     "Data em que o valor recebido foi creditado ao Beneficiário (DDMMAA)."),
    ("Nome do Pagador", 302, 337,
     "Nome do Pagador, com 36 posições (na remessa são 40)."),
    ("Identificador do complemento", 338, 338,
     "'I' quando a conta cobrança é nova, de 10 posições; a última posição e o dígito vêm em 384-385. Só vem quando a conta movimento é diferente da conta cobrança (nota 2)."),
    ("Código da moeda", 339, 340,
     "Código da moeda: '00', o único conteúdo previsto no manual."),
    ("Valor do boleto em outra unidade", 341, 353,
     "Valor do boleto em outra unidade de valor (5 casas decimais). O manual indica que não se aplica."),
    ("Valor do IOF em outra unidade", 354, 366,
     "Valor do IOF em outra unidade de valor (5 casas decimais). O manual indica que não se aplica."),
    ("Valor do débito ou crédito", 367, 379,
     "Valor do lançamento deste evento, com 2 casas decimais sem vírgula; se é débito ou crédito, diz a posição 380."),
    ("Identificação do lançamento", 380, 380,
     "Tipo do lançamento em 367-379: 'D' = débito, 'C' = crédito."),
    ("Uso Reservado (Filler)", 381, 383,
     "Reservado para uso do Banco (3 posições); preenchido com brancos."),
    ("Complemento", 384, 385,
     "Última posição da conta cobrança nova e o dígito, junto com 'I' na posição 338. O manual declara tamanho 1 para estas 2 posições; aqui vale a posição (nota 2)."),
    ("Sigla da empresa no sistema", 386, 389,
     "Sigla da empresa no sistema do banco."),
    ("Uso Reservado (Filler)", 390, 391,
     "Reservado para uso do Banco (2 posições); preenchido com brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Número sequencial do arquivo de retorno (nota 32)."),
    ("Número Sequencial do registro no arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# Qrcode Retorno
QRCODE_RETORNO_FIELDS = [
    ("Código do Registro", 1, 1,
     "Tipo do registro: '2' no retorno traz os dados do QR Code Pix do boleto. É opcional: o Beneficiário pede ao banco para recebê-lo. Vem na confirmação da entrada dos boletos registrados com QR Code e nas liquidações e baixas por Pix."),
    ("Tipo de Chave DICT / Brancos", 2, 2,
     "Tipo da chave Pix ('1' CPF, '2' CNPJ, '3' celular, '4' e-mail, '5' EVP (chave aleatória)) ou brancos (nota 34)."),
    ("Código Chave DICT/URL Gerada", 3, 79,
     "Chave Pix do Beneficiário ou URL gerada pelo Santander para o QR Code Dinâmico. Com ela a empresa gera a imagem do QR Code (responsabilidade do Beneficiário, pelas regras do Banco Central) ou compartilha o link com o Pagador (notas 35 e 36)."),
    ("Código de identificação do Qr Code (TXID)", 80, 114,
     "Identificador do QR Code (TXID) do boleto: o que o Beneficiário informou ou o que o banco gerou (nota 37)."),
    ("Uso Reservado (Filler)", 115, 391,
     "Reservado para uso do Banco (277 posições); preenchido com brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Número sequencial do arquivo de retorno (nota 32)."),
    ("Número Sequencial do Registro no Arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# Trailer Retorno
TRAILER_RETORNO_FIELDS = [
    ("Código de registro", 1, 1,
     "Tipo do registro: '9' identifica o Trailer, a última linha do arquivo."),
    ("Código da remessa", 2, 2,
     "'2' = arquivo de retorno."),
    ("Código do Serviço", 3, 4,
     "Código do serviço: '01' = Cobrança."),
    ("Código do banco", 5, 7,
     "Código do Santander na compensação: '033' (o manual também aceita '353', código legado)."),
    ("Uso Reservado (Filler)", 8, 17,
     "Reservado para uso do Banco (10 posições); preenchido com brancos."),
    ("Quantidade de registros na cobrança Simples", 18, 25,
     "Quantidade de boletos da carteira Simples informados neste retorno."),
    ("Valor total dos boletos na cobrança Simples", 26, 39,
     "Soma dos valores dos boletos da carteira Simples neste retorno, com 2 casas decimais sem vírgula."),
    ("Número do aviso de cobrança Simples", 40, 47,
     "Número do aviso de cobrança da carteira Simples."),
    ("Uso Reservado (Filler)", 48, 97,
     "Reservado para uso do Banco (50 posições); preenchido com brancos."),
    ("Quantidade de registros na cobrança caucionada", 98, 105,
     "Quantidade de boletos da carteira Caucionada informados neste retorno."),
    ("Valor total dos boletos na cobrança caucionada", 106, 119,
     "Soma dos valores dos boletos da carteira Caucionada neste retorno, com 2 casas decimais sem vírgula."),
    ("Número do aviso da cobrança caucionada", 120, 127,
     "Número do aviso de cobrança da carteira Caucionada."),
    ("Uso Reservado (Filler)", 128, 137,
     "Reservado para uso do Banco (10 posições); preenchido com brancos."),
    ("Quantidade de registros na cobrança descontada", 138, 145,
     "Quantidade de boletos da carteira Descontada informados neste retorno."),
    ("Valor total dos boletos na cobrança descontada", 146, 159,
     "Soma dos valores dos boletos da carteira Descontada neste retorno, com 2 casas decimais sem vírgula."),
    ("Número do aviso da cobrança descontada", 160, 167,
     "Número do aviso de cobrança da carteira Descontada."),
    ("Uso Reservado (Filler)", 168, 391,
     "Reservado para uso do Banco (224 posições); preenchido com brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Número sequencial do arquivo de retorno (nota 32)."),
    ("Número Sequencial do registro do arquivo", 395, 400,
     "Número da linha no arquivo: o Header é '000001' e cada linha seguinte soma 1."),
]

# --- Tabelas de código ------------------------------------------------------------------------

COMANDO_REMESSA_CODES = {  # nota 21: código de movimento da remessa (posições 109-110 do Movimento)
    "01": "Entrada do boleto",
    "02": "Baixa do boleto",
    "04": "Concessão de abatimento",
    "05": "Cancelamento do abatimento",
    "06": "Alteração do vencimento",
    "07": "Alteração do número controle beneficiário",
    "08": "Alteração do Seu Número",
    "09": "Protestar",
    "15": "Transferência da carteira Simples para Cessão",
    "16": "Baixa de Cessão por Descaracterização",
    "17": "Baixa de Cessão por Pagamento",
    "18": "Sustar o protesto (Após início do ciclo de protesto)",
    "47": "Alteração do valor nominal do boleto",
    "48": "Alteração do valor mínimo/percentual",
    "49": "Alteração do valor máximo/percentual",
}

OCORRENCIA_CODES = {  # nota 29: código de movimento do retorno (posições 109-110 do Movimento)
    "01": "Boleto não existe",
    "02": "Entrada boleto Confirmada",
    "03": "Entrada e instrução de boleto Rejeitada",
    "04": "Transferência para carteira Simples",
    "05": "Transferência para Carteira Penhor/Desconto/Cessão",
    "06": "Liquidação do Boleto Efetivada",
    "07": "Liquidação por Conta",
    "08": "Liquidação por Saldo",
    "09": "Baixa Automática",
    "10": "Boleto Baixado Conforme Instrução",
    "11": "Boletos em carteira (em ser)",
    "12": "Abatimento Concedido",
    "13": "Abatimento Cancelado",
    "14": "Alteração de Vencimento",
    "15": "Confirmação de Protesto",
    "16": "Boleto Baixado/Liquidado",
    "17": "Liquidado em Cartório",
    "21": "Boleto Enviado a Cartório",
    "22": "Boleto Retirado do Cartório",
    "24": "Custas de Cartório",
    "25": "Boleto Protestado",
    "26": "Sustar Protesto",
    "27": "Cancelar Boleto Protestado",
    "35": "Boleto DDA Reconhecido pelo Pagador",
    "36": "Boleto DDA Não Reconhecido pelo Pagador",
    "37": "Boleto DDA Recusado pela PCR",
    "38": "Não Protestar (antes de iniciar o ciclo de protesto)",
    "39": "Espécie de Boleto não permite a instrução",
    "61": "Confirmação de Alteração do Valor Nominal do Boleto",
    "62": "Confirmação de Alteração do Valor ou Percentual mínimo",
    "63": "Confirmação de Alteração do Valor ou Percentual máximo",
    "93": "Pagamento do Boleto Recebido",
    "94": "Cancelamento do Pagamento Recebido",
}

ESPECIE_BOLETO_CODES = {  # nota 24: espécie do boleto (posições 148-149)
    "01": "DM Duplicata Mercantil",
    "02": "NP Nota Promissória",
    "03": "AP Apólice de Seguro",
    "05": "RC Recibo",
    "06": "DS Duplicata de Serviço",
    "07": "LC Letra de Cambio",
    "08": "BDP Boleto de Proposta",
    "19": "BCC Boleto de Cartão de Crédito",
    "33": "BDA Boleto de Depósito e Aporte (Nota 33)",
}

INSTRUCAO_CODES = {  # nota 25: primeira e segunda instrução (posições 157-160)
    "00": "Não há instruções",
    "02": "Baixar após quinze dias do vencimento",
    "03": "Baixar após 30 dias do vencimento",
    "04": "Não Baixar",
    "06": "Protestar (Vide posição 392/393)",
    "07": "Não Protestar",
    "08": "Não cobrar juros de mora",
}

ERRO_OCORRENCIA_CODES = {  # nota 31: códigos de erro/ocorrência do retorno (posições 137-145)
    "001": "Nosso Número não numérico",
    "002": "Valor do abatimento não numérico",
    "003": "Data do vencimento não numérica",
    "004": "Cobrança não numérica",
    "005": "Código da carteira não numérica",
    "006": "Código da carteira inválida",
    "007": "Espécie do documento invalida",
    "008": "Unidade de valor não numérica",
    "009": "Baixa não permitida - boleto penhor com garantia / Unidade de valor inválida",
    "010": "Código primeira instrução não numérica",
    "011": "Código segunda instrução não numérica",
    "012": "Valor do boleto em outra unidade",
    "013": "Valor do boleto não numérico",
    "014": "Valor de mora não numérico",
    "015": "Data emissão não numérica",
    "016": "Data de vencimento inválida",
    "017": "Código da agência cobradora não numérica",
    "018": "Valor do IOF não numérico",
    "019": "Número do CEP não numérico",
    "020": "Tipo de inscrição não numérica",
    "021": "Número do CNPJ ou CPF não numérico",
    "022": "Código de ocorrência inválido",
    "023": "Boleto liquidado",
    "024": "Total parcela não numérico",
    "025": "Valor desconto não numérico",
    "026": "Código banco cobrador inválido",
    "027": "Número parcelas carnê não numérico",
    "028": "Número parcelas carnê zerado",
    "029": "Valor de mora inválido",
    "030": "Data vencimento menor de quinze dias da data processamento",
    "031": "Instrução recusada pelo sistema de garantias",
    "038": "Movimento excluído por solicitação",
    "039": "Perfil não aceita boleto em banco correspondente",
    "040": "Cobrança rápida não aceita banco correspondente",
    "041": "Agência cobradora não encontrada",
    "042": "Conta cobrança inválida",
    "043": "Não baixar, complemento informado inválido",
    "044": "Não protestar, complemento informado inválido",
    "045": "Quantidade de dias para baixa não preenchido",
    "046": "Quantidade de dias para protesto não preenchido",
    "047": "Total parcelas informada não bate com o total de parcelas geradas",
    "048": "Carnê com parcelas com erro",
    "049": "Seu número não confere com o carnê",
    "050": "Número do boleto igual a zero",
    "051": "Boleto não encontrado",
    "052": "Ocorrência não acatada, boleto liquidado",
    "053": "Ocorrência não acatada, boleto baixado",
    "054": "Boleto com ordem de protesto já emitida",
    "055": "Ocorrência não acatada para boleto já protestado",
    "056": "Ocorrência não acatada, boleto não vencido",
    "057": "CEP do pagador incorreto",
    "058": "CNPJ/CPF incorreto",
    "059": "Instrução não permitida para o tipo de carteira / Instrução aceita apenas para cobrança simples",
    "060": "Espécie do documento não protestavel",
    "061": "Beneficiário sem carta de protesto",
    "062": "Pagador não protestavel",
    "063": "CEP não encontrado na tabela de praças",
    "064": "Tipo de cobrança não permite protesto",
    "065": "Pedido de sustação já solicitado",
    "066": "Sustação de protesto fora do prazo",
    "067": "Cliente não transmite registro de ocorrência",
    "068": "Tipo de vencimento inválido",
    "069": "Produto diferente da cobrança simples",
    "070": "Data prorrogação menor que a data do vencimento",
    "071": "Data antecipação maior que a data do vencimento",
    "072": "Data do documento superior a data da instrução",
    "073": "Abatimento maior ou igual ao valor do boleto",
    "074": "Primeiro desconto maior ou igual o valor do boleto",
    "075": "Segundo desconto maior ou igual valor do boleto",
    "076": "Terceiro desconto maior ou igual valor do boleto",
    "077": "Desconto por antecipação maior ou igual valor do boleto",
    "078": "Não existe abatimento para cancelar",
    "079": "Não existe primeiro desconto para cancelar",
    "080": "Não existe segundo desconto para cancelar",
    "081": "Não existe terceiro desconto para cancelar",
    "082": "Não existe desconto por antecipação para cancelar",
    "083": "Não existe multa por atraso para cancelar",
    "084": "Já existe o segundo desconto",
    "085": "Já existe o terceiro desconto",
    "086": "Data segundo desconto inválida",
    "087": "Data do terceiro desconto inválida",
    "088": "Data da instrução inválida",
    "089": "Data multa menor ou igual do vencimento",
    "090": "Existe desconto por antecipação",
    "091": "Tipo/número de inscrição do pagador inválido",
    "092": "Nosso número já cadastrado",
    "093": "Valor do boleto não informado",
    "094": "Valor boleto em outra moeda não informada",
    "095": "Perfil não aceita valor do boleto zerado",
    "096": "Espécie do documento não permite protesto",
    "097": "Espécie documento não permite IOF zerado",
    "098": "Data emissão inválida",
    "099": "Registro duplicado no movimento diário",
    "100": "Data emissão maior que a data de vencimento",
    "101": "Nome do Pagador não informado",
    "102": "Endereço do pagador não informado",
    "103": "Cidade do Pagador não informado",
    "104": "Unidade da federação não informada",
    "105": "Tipo de inscrição não existe",
    "106": "CNPJ/CPF não informado",
    "107": "Unidade da federação",
    "108": "Dígito CNPJ/CPF incorreto / Digito CNPJ/CPF incorreto",
    "109": "Valor de mora tem quer ser zero (boleto=zero)",
    "110": "Data do primeiro desconto inválida",
    "111": "Data desconto não numérica",
    "112": "Valor desconto não informado",
    "113": "Valor desconto inválido",
    "114": "Valor abatimento não informado",
    "115": "Valor abatimento maior que o valor do boleto",
    "116": "Data multa não numérico",
    "117": "Valor do abatimento é maior que o valor do boleto",
    "118": "Data multa não informado",
    "119": "Data multa maior que a data de vencimento",
    "120": "Percentual multa não numérico",
    "121": "Percentual multa não informado",
    "122": "Valor IOF maior que o valor do boleto",
    "123": "CEP do pagador não numérico",
    "124": "CEP do pagador não encontrado",
    "125": "Complemento da instrução não numérico",
    "128": "Código de protesto inválido",
    "129": "Espécie do documento não numérica",
    "130": "Forma de cadastramento não numérica",
    "131": "Forma de cadastramento inválida",
    "132": "Forma de cadastramento 2 invalida para carteira tipo 3",
    "133": "Forma de cadastramento 2 invalida para carteira tipo 4",
    "134": "Código do movimento remessa não numérico",
    "136": "Código banco na compensação não numérico",
    "137": "Código do banco na compensação inválido",
    "138": "Número do lote remessa detalhe não numérico",
    "139": "Tipo de registro inválido",
    "140": "Código segmento do registro detalhe inválido",
    "141": "Número sequencial do registro detalhe inválido",
    "142": "Número da agência cedente/digito não numérico",
    "143": "Número da conta cedente/dígito não numérico",
    "144": "Tipo de documento não numérico",
    "145": "Tipo de documento inválido",
    "146": "Código de protesto não numérico",
    "147": "Quantidade de dias para protesto inválido",
    "148": "Quantidade de dias para protesto não numérico",
    "149": "Código de mora inválido",
    "150": "Código de mora não numérico",
    "151": "Valor mora igual a zeros para o código de mora 1",
    "152": "Valor taxa mora igual a zeros para o código de cod mora 2",
    "153": "Valor mora diferente de zeros para código de mora 3",
    "154": "Valor mora não numérico para código de mora 2",
    "155": "Valor de mora inválido para código de mora 4",
    "156": "Quantidade de dias para baixa/devolução não numérico",
    "157": "Quantidade de dias baixa/devolução inválido para o código 1",
    "158": "Quantidade de dias baixa/devolução inválido para o código 2",
    "159": "Quantidade de dias baixa/devolução inválido para o código 3",
    "160": "Bairro do Pagador não informado",
    "161": "Tipo de inscrição CNPJ/CPF beneficiário final não numérico",
    "162": "Indicador de carnê não numérico",
    "163": "Número total de parcelas carnê inválido",
    "164": "Número do plano não numérico",
    "165": "Indicador de parcelas carnê inválido",
    "166": "Número sequencial de parcelas inválidas para indicador maior que zeros",
    "167": "Número sequencial de parcelas invalidas para indicador diferente de zeros",
    "168": "Número total parcelas inválidas para indicador maior que zeros",
    "169": "Número total de parcelas invalidas para indicador diferente de zeros",
    "170": "Forma de cadastramento 2 invalido para carteira tipo 5",
    "199": "Tipo inscrição CNPJ/CPF beneficiário final inválido",
    "200": "Número inscrição CNPJ beneficiário final inválido",
    "201": "Alteração do controle participante inválido",
    "202": "Alteração do Seu Número inválido",
    "371": "Boleto rejeitado - Operação de desconto",
    "372": "Boleto rejeitado - Horário limite operação desconto",
    "373": "Quantidade pagamentos possíveis inválidos",
    "374": "Valor nominal maior que o valor máximo do boleto",
    "375": "Valor nominal menor que o valor máximo do boleto",
    "378": "Tipo de valor inválido",
    "379": "Valor máximo inválido",
    "380": "Percentual máximo invalido / Percentual máximo inválido",
    "381": "Valor mínimo inválido",
    "382": "Percentual mínimo inválido",
    "383": "Instrução exige o registro tipo 8",
    "384": "Valor nominal incompatível com o tipo de pagamento",
    "385": "Valor nominal incompatível com espécie / Valor nominal incompatível com a espécie",
    "388": "Tipo de pagamento não numérico",
    "389": "Tipo de pagamento inválido",
    "390": "Quantidade de pagamentos possíveis não numéricos",
    "391": "Instrução não permitida para o boleto com reserva",
    "414": "Transferência não permitida",
    "417": "Operação Rejeitada – Horário Limite Excedido",
    "418": "Não foi realizada a contratação do produto SX Integra para operar com Cessão",
    "419": "Operação de Cessão Não Confirmada",
    "420": "Operação de Cessão Rejeitada – Ver detalhes no relatório do SX Integra",
    "494": "CNPJ Raiz do pagador não pode ser igual ao do beneficiário original",
    "497": "CPF do pagador não pode ser igual ao do beneficiário original",
    "500": "Registro não permitido – Beneficiário Final com restrição",
    "501": "Chave PIX Inválida",
    "502": "Chave PIX Sem Cadastro na DICT",
    "503": "Chave PIX Não é Compatível com CNPJ/CPF",
    "504": "Identificador Txid em duplicidade",
    "505": "Identificador Txid inválido ou não encontrado",
    "506": "Alteração não permitida - QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "507": "Cancelamento não permitido – QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "508": "Registrado com QR Code Pix",
    "509": "Registrado sem QR Code Pix",
    "510": "Baixado por Pagamento via Pix",
    "511": "Liquidado por Pagamento via Pix",
    "513": "Código de Moeda Inválido",
    "514": "Obrigatório informar o Beneficiário Final para o boleto",
    "515": "Instrução recusada - limite de alt.de vencto atingido p/ boletos em garantia",
    "516": "Instrução recusada, convenio com garantia em conta Escrow",
    "517": "Instrução não aceita – Pix Automático",
}
