"""
CNAB 240 Santander (banco 033) - Cobrança - referência de campos.

Fonte: "Layout Cobrança H7815 - CNAB 240 posições - padrão Santander/Multibanco", versão 8.5, fevereiro/2026
(manual oficial do Banco Santander, https://www.santander.com.br/layout-de-arquivos). As notas citadas nas
descrições são as notas desse manual.

Estrutura (posição 8 = tipo de registro; posição 14 = segmento do Registro Detalhe):
  Remessa: Header de Arquivo (0), Header de Lote (1), Segmentos P e Q (obrigatórios), R, S (opcionais), Y-03 e Y-53 (opcionais),
           Trailer de Lote (5), Trailer de Arquivo (9).
  Retorno: Header de Arquivo, Header de Lote, Segmentos T e U (obrigatórios), Y-03 e Y-04 (opcionais),
           Trailer de Lote, Trailer de Arquivo.

O Segmento S tem dois formatos, escolhidos pela posição 18 ("Identificação da impressão"): 1 = formulário
especial (mensagem por linha) e 2 = mensagens 5 a 9. Aqui são as listas SEGMENTO_S_1_REMESSA_FIELDS e
SEGMENTO_S_2_REMESSA_FIELDS.
O Segmento Y traz o sub-código nas posições 18-19 ("Identificação do Registro": 03 = QR Code/PIX,
53 = tipo de pagamento, 04 = cheque no retorno).

Convenções de nome (a interface depende delas): o resumo da grade procura por trechos como "Data de
Vencimento", "Valor Nominal", "Nosso Número", "Número do Documento", "Código de Movimento", "Nome do
Pagador" e "Valor Pago"; campos reservados levam "Uso Reservado (Filler)" e aparecem acinzentados. Por
isso alguns títulos trazem, entre parênteses, o nome que o manual usa.

Observações sobre o manual: o Header de Arquivo da remessa mostra o banco como "33" (nas demais linhas é
"033"); o Segmento P chama a agência e a conta do Beneficiário de "Destinatária" (aqui, "Destinatário").
"""

# --- Remessa ----------------------------------------------------------------------------------

# HEADER_ARQUIVO_REMESSA_FIELDS
HEADER_ARQUIVO_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033' (neste registro o manual mostra '33')."),
    ("Lote de serviço", 4, 7,
     "Lote de serviço: '0000' no Header de Arquivo (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '0' = Header de Arquivo. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Uso Reservado (Filler)", 9, 16,
     "Reservado para uso do Banco (8 posições); preenchido com brancos."),
    ("Tipo de inscrição da empresa", 17, 17,
     "Tipo do documento da empresa (o Beneficiário): '1' = CPF, '2' = CNPJ."),
    ("Inscrição da empresa", 18, 32,
     "CPF ou CNPJ da empresa, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 54)."),
    ("Código de Transmissão", 33, 47,
     "Código de transmissão: informação cedida pelo Santander que identifica o arquivo remessa do cliente (nota 3)."),
    ("Uso Reservado (Filler)", 48, 72,
     "Reservado para uso do Banco (25 posições); preenchido com brancos."),
    ("Nome da empresa", 73, 102,
     "Nome da empresa beneficiária: quem emite os boletos e recebe os pagamentos."),
    ("Nome do Banco", 103, 132,
     "Texto 'Banco Santander', o nome do banco."),
    ("Uso Reservado (Filler)", 133, 142,
     "Reservado para uso do Banco (10 posições); preenchido com brancos."),
    ("Código remessa", 143, 143,
     "'1' = arquivo de remessa, enviado pelo Beneficiário ao banco (no retorno é '2')."),
    ("Data de geração do arquivo", 144, 151,
     "Data em que o arquivo foi gerado, no formato DDMMAAAA."),
    ("Uso Reservado (Filler)", 152, 157,
     "Reservado para uso do Banco (6 posições); preenchido com brancos."),
    ("Nº seqüencial do arquivo", 158, 163,
     "Número sequencial do arquivo, controlado por quem gera o arquivo para ordenar os arquivos enviados: aumenta 1 a cada Header de Arquivo (nota 4)."),
    ("Nº da versão do layout do arquivo", 164, 166,
     "Versão do layout do arquivo: '040'."),
    ("Uso Reservado (Filler)", 167, 240,
     "Reservado para uso do Banco (74 posições); preenchido com brancos."),
]

# HEADER_LOTE_REMESSA_FIELDS
HEADER_LOTE_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote remessa", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '1' = Header de Lote. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Tipo de operação", 9, 9,
     "Tipo de operação: 'R' = Remessa (no retorno é 'T')."),
    ("Tipo de serviço", 10, 11,
     "Tipo de serviço: '01' = Cobrança."),
    ("Uso Reservado (Filler)", 12, 13,
     "Reservado para uso do Banco (2 posições); preenchido com brancos."),
    ("Nº da versão do layout do lote", 14, 16,
     "Versão do layout do lote: '030' na remessa (para o retorno o manual indica '040')."),
    ("Uso Reservado (Filler)", 17, 17,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Tipo de inscrição da empresa", 18, 18,
     "Tipo do documento da empresa (o Beneficiário): '1' = CPF, '2' = CNPJ."),
    ("Inscrição da empresa", 19, 33,
     "CPF ou CNPJ da empresa, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 54)."),
    ("Uso Reservado (Filler)", 34, 53,
     "Reservado para uso do Banco (20 posições); preenchido com brancos."),
    ("Código de Transmissão", 54, 68,
     "Código de transmissão: informação cedida pelo Santander que identifica o arquivo remessa do cliente (nota 3)."),
    ("Uso Reservado (Filler)", 69, 73,
     "Reservado para uso do Banco (5 posições); preenchido com brancos."),
    ("Nome do Beneficiário", 74, 103,
     "Nome do Beneficiário: a empresa que emite os boletos."),
    ("Mensagem 1", 104, 143,
     "Mensagem 1: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação, em todos os boletos do lote. Não volta no retorno. As mensagens 3 e 4 do Segmento R, quando preenchidas, substituem as mensagens 1 e 2 (notas 9 e 33)."),
    ("Mensagem 2", 144, 183,
     "Mensagem 2: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação, em todos os boletos do lote. Não volta no retorno. As mensagens 3 e 4 do Segmento R, quando preenchidas, substituem as mensagens 1 e 2 (notas 9 e 33)."),
    ("Número remessa/retorno", 184, 191,
     "Número da remessa: adotado e controlado por quem gera o arquivo, para identificar a sequência de envio dos arquivos entre o Beneficiário e o banco (nota 10)."),
    ("Data da gravação remessa/retorno", 192, 199,
     "Data da gravação da remessa, no formato DDMMAAAA."),
    ("Uso Reservado (Filler)", 200, 240,
     "Reservado para uso do Banco (41 posições); preenchido com brancos."),
]

# SEGMENTO_P_REMESSA_FIELDS
SEGMENTO_P_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote remessa", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'P' = dados do boleto, obrigatório na remessa (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Código de movimento remessa", 16, 17,
     "Instrução que o Beneficiário comanda para o boleto. '01' registra o boleto (entrada, com os Segmentos P e Q); os demais agem sobre um boleto já registrado e só usam o Segmento P: '02' baixa, '04'/'05' conceder ou cancelar abatimento, '06' alterar vencimento, '07'/'08' alterar o controle do participante e o Seu Número, '09' protestar, '18' sustar o protesto, '98' não protestar (antes do ciclo de protesto), '10'/'11' conceder ou cancelar desconto, '12' transferência de titularidade automática, '31' alterar outros dados (tipo e dias de protesto) e '47' a '49' alterar o valor nominal, o mínimo ou o máximo. '15' a '17' são da carteira de Cessão (produto SX Integra). Tabela completa em MOVIMENTO_REMESSA_CODES (nota 14)."),
    ("Agência do Destinatário", 18, 21,
     "Agência do Beneficiário, sem o dígito (o manual chama de \"Agência do Destinatário\")."),
    ("Dígito da Agência do Destinatário", 22, 22,
     "Dígito da agência do Beneficiário."),
    ("Número da conta corrente", 23, 31,
     "Conta corrente do Beneficiário, 9 posições, sem o dígito."),
    ("Dígito verificador da conta", 32, 32,
     "Dígito verificador da conta corrente do Beneficiário."),
    ("Conta cobrança Destinatário FIDC", 33, 41,
     "Conta cobrança de destino na transferência de carteira: com o movimento '12' (transferência de titularidade automática, carteira FIDC), a conta do convênio que vai receber os boletos transferidos. O manual remete à nota 45, mas quem trata deste campo é a nota 44."),
    ("Dígito da conta cobrança Destinatário FIDC", 42, 42,
     "Dígito da conta cobrança de destino da transferência (FIDC) (nota 44)."),
    ("Uso Reservado (Filler)", 43, 44,
     "Reservado para uso do Banco (2 posições); preenchido com brancos."),
    ("Nosso Número (Identificação do boleto no Banco)", 45, 57,
     "Nosso Número: número do boleto no banco e \"chave\" do boleto entre banco e cliente, com o dígito calculado por módulo 11 (pesos 2 a 9 da direita para a esquerda; resto 0 ou 1 dá dígito 0 e resto 10 dá dígito 1). Recomenda-se informar; zerado, o banco numera se o convênio permitir. É obrigatório na Cobrança Rápida com Registro, em que o Beneficiário emite o boleto. Para seguradoras, as 2 primeiras posições trazem o código de recolhimento do IOF (nota 15)."),
    ("Tipo de cobrança", 58, 58,
     "Carteira: '1' Cobrança Simples (Sem Registro e Eletrônica com Registro); '3' Caucionada; '4' Descontada; '5' Simples (Rápida com Registro), a carteira do boleto com QR Code; '6' Caucionada (Rápida com Registro); '7' e '9' Transferência de Titularidade sem e com devolução (FIDC); '8' Cessão (produto SX Integra); 'B' Simples Sem Registro, para registrar boletos já impressos, só na entrada (notas 5 e 45)."),
    ("Forma de Cadastramento", 59, 59,
     "Forma de cadastramento: '1' Cobrança Registrada (Rápida e Eletrônica com Registro); '2' Cobrança sem Registro; '3' Cobrança Simples sem registro, sem ou com pré-impresso, para boletos já na praça, só na entrada. O boleto com QR Code Pix usa a carteira '5' com a forma '1' (notas 6 e 45)."),
    ("Tipo de documento", 60, 60,
     "Tipo de documento: '1' = Tradicional, '2' = Escritural."),
    ("Uso Reservado (Filler)", 61, 61,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Uso Reservado (Filler)", 62, 62,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Número do Documento (Seu Número)", 63, 77,
     "Seu Número: número adotado e controlado pelo Beneficiário para identificar o documento cobrado (número da duplicata, da apólice etc.). Volta no retorno. Para boletos com protesto, use até 11 posições, essencial para o andamento no cartório (nota 16)."),
    ("Data de vencimento do boleto", 78, 85,
     "Data de vencimento do boleto (DDMMAAAA). Deve ser válida, posterior à entrada do boleto e no máximo 10 anos depois dela; '11111111' ou '99999999' é rejeitado. Não se pode usar 'Contra Apresentação' nem 'À vista' (nota 17)."),
    ("Valor nominal do boleto", 86, 100,
     "Valor nominal do boleto, com 2 casas decimais sem vírgula. Só as espécies BCC (31) e BDP (32) aceitam valor zerado e alteração do valor nominal (nota 18)."),
    ("Agência encarregada da cobrança FIDC", 101, 104,
     "Agência encarregada da cobrança: atribuída pelo banco a partir do CEP do Pagador. Com o movimento '12' (transferência de titularidade automática), é a agência do cessionário que recebe a carteira transferida (notas 19 e 44)."),
    ("Dígito da Agência do Beneficiário FIDC", 105, 105,
     "Dígito da agência encarregada da cobrança (FIDC) (nota 44)."),
    ("Uso Reservado (Filler)", 106, 106,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Espécie do boleto", 107, 108,
     "Espécie do boleto: '02' DM Duplicata Mercantil, '04' DS Duplicata de Serviço, '07' LC Letra de Câmbio (banco 353), '30' LC Letra de Câmbio (banco 008), '12' NP Nota Promissória, '13' NR Nota Promissória Rural, '17' RC Recibo, '20' AP Apólice de Seguro, '31' BCC Cartão de Crédito, '32' BDP Boleto de Proposta, '33' BDA Boleto de Depósito e Aporte, '97' CH Cheque, '98' ND Nota Promissória Direta (ver ESPECIE_BOLETO_CODES). BCC e BDP não aceitam multa, juros, desconto, abatimento nem protesto; no BDA o Pagador tem de ser o Beneficiário Final (nota 20)."),
    ("Identif. de boleto Aceito/Não Aceito", 109, 109,
     "Aceite do boleto: 'N' = não aceite, o único conteúdo previsto no manual."),
    ("Data da emissão do boleto", 110, 117,
     "Data de emissão do boleto (DDMMAAAA); não pode ser posterior à data de entrada no banco (rejeição 25 da nota 40-A)."),
    ("Código de juros de mora", 118, 118,
     "Código dos juros de mora: '1' valor por dia; '2' taxa mensal, aplicada sobre o valor e calculada por dia de atraso; '3' isento; '4' comissão de permanência do banco, sem taxa no arquivo; '5' tolerância com valor por dia e '6' tolerância com taxa mensal, com juros só a partir da data em 119-126 (nota 21)."),
    ("Data de juros de mora", 119, 126,
     "Data a partir da qual correm os juros (DDMMAAAA): a data de vencimento nos códigos 1, 2 e 4. Nos códigos 5 e 6 (tolerância) pode ser posterior ao vencimento, e até ela não há juros (nota 22)."),
    ("Valor da mora/dia ou Taxa mensal", 127, 141,
     "Valor dos juros por dia (códigos 1 e 5) ou taxa mensal (códigos 2 e 6), com 2 casas decimais sem vírgula; vazio no código 4. A tabela indica 2 casas decimais, mas a nota 18 fala em 5 casas para taxas de juros (notas 18 e 21)."),
    ("Código do desconto 1", 142, 142,
     "Código do primeiro desconto: '0' isento; '1' valor fixo até a data informada; '2' percentual até a data informada; '3' valor por antecipação por dia corrido; '4' valor por antecipação por dia útil (nota 23)."),
    ("Data de desconto 1", 143, 150,
     "Data limite do primeiro desconto (DDMMAAAA): maior que a emissão e menor ou igual ao vencimento nos códigos 1 e 2, e igual ao vencimento nos códigos 3 e 4. Pode haver até três descontos (o segundo e o terceiro vão no Segmento R), cada um numa data diferente (nota 23)."),
    ("Valor ou Percentual do desconto concedido", 151, 165,
     "Valor (códigos 1, 3 e 4) ou percentual (código 2) do primeiro desconto, com 2 casas decimais sem vírgula. Deve ser menor que o valor nominal (notas 18 e 23)."),
    ("Percentual do IOF a ser recolhido", 166, 180,
     "Percentual do IOF a recolher, com 5 casas decimais sem vírgula: informe quando o convênio não tem o IOF cadastrado no perfil (nota 18)."),
    ("Valor do abatimento", 181, 195,
     "Valor do abatimento, com 2 casas decimais sem vírgula. Deve ser menor que o valor nominal, e a soma de desconto e abatimento também (nota 18)."),
    ("Identificação do boleto na empresa", 196, 220,
     "Número de controle do participante, opcional: identificação livre do boleto no sistema do Beneficiário, devolvida no retorno quando o boleto é liquidado (nota 24)."),
    ("Código para protesto", 221, 221,
     "Código para protesto: '0' não protestar; '1' protestar em dias corridos; '2' em dias úteis; '3' usar o perfil do Beneficiário; '9' cancelamento de protesto automático. A quantidade de dias vai em 222-223 (nota 25)."),
    ("Número de dias para protesto", 222, 223,
     "Quantidade de dias para protesto, contados como diz o código em 221 (corridos ou úteis)."),
    ("Código para Baixa/Devolução", 224, 224,
     "Código para baixa/devolução: '1' baixar/devolver; '2' não baixar/não devolver; '3' usar o perfil do Beneficiário. A quantidade de dias vai em 226-227 (nota 26)."),
    ("Uso Reservado (Filler)", 225, 225,
     "Reservado para uso do Banco (1 posições); preenchido com zero fixo."),
    ("Número de dias para Baixa/Devolução", 226, 227,
     "Quantidade de dias para a baixa/devolução do boleto (ver o código em 224). No BDA registrado sem prazo de baixa, o banco assume 30 dias (nota 20)."),
    ("Código da moeda", 228, 229,
     "Código da moeda: '00' = Real (nota 27)."),
    ("Uso Reservado (Filler)", 230, 240,
     "Reservado para uso do Banco (11 posições); preenchido com brancos."),
]

# SEGMENTO_Q_REMESSA_FIELDS
SEGMENTO_Q_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote remessa", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº seqüencial do registro no lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'Q' = dados do Pagador e do Beneficiário Final, obrigatório na entrada de boletos (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Código de movimento remessa", 16, 17,
     "Código de movimento da remessa, o mesmo do Segmento P do boleto: é por ele e pelo número do registro que o banco junta os segmentos de um mesmo boleto. Tabela em MOVIMENTO_REMESSA_CODES (nota 14)."),
    ("Tipo de inscrição do Pagador", 18, 18,
     "Tipo do documento do Pagador: '1' = CPF, '2' = CNPJ. O documento é obrigatório e tem o dígito conferido. Não pode ser igual ao do Beneficiário original nem ao do Beneficiário Final (nem a raiz do CNPJ), a não ser na espécie 33, BDA (nota 29)."),
    ("Inscrição do Pagador", 19, 33,
     "CPF ou CNPJ do Pagador, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 54)."),
    ("Nome do Pagador", 34, 73,
     "Nome de quem vai pagar o boleto. Obrigatório: sem ele a entrada é rejeitada (rejeição 45 da nota 40-A)."),
    ("Endereço do Pagador", 74, 113,
     "Endereço do Pagador (logradouro, número e complemento). Obrigatório (nota 28)."),
    ("Bairro do Pagador", 114, 128,
     "Bairro do Pagador. Obrigatório (nota 28)."),
    ("Cep do Pagador", 129, 133,
     "Cinco primeiros dígitos do CEP do Pagador. Obrigatório; CEP inválido ou sem praça de cobrança volta com as rejeições 48 e 49 da nota 40-A (nota 28)."),
    ("Sufixo do Cep do Pagador", 134, 136,
     "Três últimos dígitos (sufixo) do CEP do Pagador (nota 28)."),
    ("Cidade do Pagador", 137, 151,
     "Cidade do Pagador. Obrigatória (nota 28)."),
    ("Unidade da Federação do Pagador", 152, 153,
     "Sigla da Unidade da Federação do Pagador. Obrigatória, precisa existir e ser válida; incompatível com o CEP volta com a rejeição 51 (nota 28)."),
    ("Tipo de inscrição Beneficiário Final", 154, 154,
     "Tipo do documento do Beneficiário Final: '1' = CPF, '2' = CNPJ (notas 29 e 30)."),
    ("Inscrição Beneficiário Final", 155, 169,
     "CPF ou CNPJ do Beneficiário Final (antigo Sacador/Avalista), alinhado à direita e completado com zeros à esquerda; aceita o CNPJ alfanumérico. Não pode ser igual ao do Beneficiário original, nem a raiz do CNPJ (notas 30 e 54)."),
    ("Nome do Beneficiário Final", 170, 209,
     "Nome do Beneficiário Final (antigo Sacador/Avalista), quem de fato recebe os recursos. Documento e nome são obrigatórios quando o boleto foi negociado com terceiros, quando os recursos vão para outro que não o Beneficiário original e no BDA, por exigência da Circular BACEN 3.956/19 (nota 30)."),
    ("Uso Reservado (Filler)", 210, 212,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 213, 215,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 216, 218,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 219, 221,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 222, 240,
     "Reservado para uso do Banco (19 posições); preenchido com brancos."),
]

# SEGMENTO_R_REMESSA_FIELDS
SEGMENTO_R_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote remessa", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Código segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'R' = outras instruções (segundo e terceiro descontos, multa e mensagens 3 e 4), opcional (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Código de movimento", 16, 17,
     "Código de movimento da remessa, o mesmo do Segmento P do boleto: é por ele e pelo número do registro que o banco junta os segmentos de um mesmo boleto. Tabela em MOVIMENTO_REMESSA_CODES (nota 14)."),
    ("Código do desconto 2", 18, 18,
     "Código do segundo desconto: '0' isento; '1' valor fixo até a data informada; '2' percentual até a data informada; '3' valor por antecipação por dia corrido; '4' valor por antecipação por dia útil (nota 23)."),
    ("Data do desconto 2", 19, 26,
     "Data limite do segundo desconto (DDMMAAAA), diferente da data dos outros descontos (nota 23)."),
    ("Valor/Percentual a ser concedido", 27, 41,
     "Valor (códigos 1, 3 e 4) ou percentual (código 2) do segundo desconto, com 2 casas decimais sem vírgula (nota 18)."),
    ("Código do desconto 3", 42, 42,
     "Código do terceiro desconto: '0' isento; '1' valor fixo até a data informada; '2' percentual até a data informada; '3' valor por antecipação por dia corrido; '4' valor por antecipação por dia útil (nota 23)."),
    ("Data do desconto 3", 43, 50,
     "Data limite do terceiro desconto (DDMMAAAA), diferente da data dos outros descontos (nota 23)."),
    ("Valor/Percentual a ser concedido", 51, 65,
     "Valor (códigos 1, 3 e 4) ou percentual (código 2) do terceiro desconto, com 2 casas decimais sem vírgula (nota 18)."),
    ("Código da multa", 66, 66,
     "Código da multa: '1' valor fixo, '2' percentual; o valor ou o percentual vai em 75-89. Neste layout não é possível usar a multa cadastrada no convênio (nota 32)."),
    ("Data da multa", 67, 74,
     "Data a partir da qual a multa incide (DDMMAAAA): a multa vale depois do dia informado; inválida ou não informada, vale a data de vencimento. O boleto mostra \"Cobrar multa após XX/XX/XXXX\" (nota 32)."),
    ("Valor/Percentual a ser aplicado", 75, 89,
     "Valor (código 1) ou percentual (código 2) da multa, com 2 casas decimais sem vírgula."),
    ("Uso Reservado (Filler)", 90, 99,
     "Reservado para uso do Banco (10 posições); preenchido com brancos."),
    ("Mensagem 3", 100, 139,
     "Mensagem 3: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação deste boleto. Quando preenchidas, as mensagens 3 e 4 substituem as mensagens 1 e 2 do Header de Lote (nota 33)."),
    ("Mensagem 4", 140, 179,
     "Mensagem 4: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação deste boleto. Quando preenchidas, as mensagens 3 e 4 substituem as mensagens 1 e 2 do Header de Lote (nota 33)."),
    ("Uso Reservado (Filler)", 180, 240,
     "Reservado para uso do Banco (61 posições); preenchido com brancos."),
]

# SEGMENTO_S_1_REMESSA_FIELDS (Segmento S, impressão 1)
SEGMENTO_S_1_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote remessa", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'S' = outras mensagens no boleto, opcional (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Código de movimento", 16, 17,
     "Código de movimento da remessa, o mesmo do Segmento P do boleto: é por ele e pelo número do registro que o banco junta os segmentos de um mesmo boleto. Tabela em MOVIMENTO_REMESSA_CODES (nota 14)."),
    ("Identificação da impressão", 18, 18,
     "Tipo de impressão: '1' = mensagem livre no recibo do Pagador, só em formulário especial, uma linha de até 100 posições por Segmento S; a nota fala em até 24 linhas (nota 34)."),
    ("Número da linha a ser impressa", 19, 20,
     "Número da linha em que o texto é impresso no recibo: de 01 a 22, na sequência; linha sem texto vai com brancos (nota 35)."),
    ("Mensagem para recibo do Pagador", 21, 21,
     "'2' = mensagem comum a todos os boletos do movimento (um único Segmento S, entre o Header de Lote e o primeiro Segmento P); '4' = mensagem só do boleto do registro anterior (nota 36)."),
    ("Mensagem a ser impressa", 22, 121,
     "Texto da linha, com até 100 caracteres, impresso no recibo do Pagador."),
    ("Uso Reservado (Filler)", 122, 240,
     "Reservado para uso do Banco (119 posições); preenchido com brancos."),
]

# SEGMENTO_S_2_REMESSA_FIELDS (Segmento S, impressão 2)
SEGMENTO_S_2_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote remessa", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'S' = outras mensagens no boleto, opcional (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com branco."),
    ("Código de movimento", 16, 17,
     "Código de movimento da remessa, o mesmo do Segmento P do boleto: é por ele e pelo número do registro que o banco junta os segmentos de um mesmo boleto. Tabela em MOVIMENTO_REMESSA_CODES (nota 14)."),
    ("Identificação da impressão", 18, 18,
     "Tipo de impressão: '2' = mensagens livres nas instruções de cobrança da ficha de compensação; só um Segmento S de código 2 por boleto (nota 34)."),
    ("Mensagem 5", 19, 58,
     "Mensagem 5: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação."),
    ("Mensagem 6", 59, 98,
     "Mensagem 6: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação."),
    ("Mensagem 7", 99, 138,
     "Mensagem 7: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação."),
    ("Mensagem 8", 139, 178,
     "Mensagem 8: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação; o manual indica brancos neste campo."),
    ("Mensagem 9", 179, 218,
     "Mensagem 9: texto livre de 40 posições impresso nas instruções de cobrança da ficha de compensação; o manual indica brancos neste campo."),
    ("Uso Reservado (Filler)", 219, 240,
     "Reservado para uso do Banco (22 posições); preenchido com brancos."),
]

# SEGMENTO_Y03_REMESSA_FIELDS
SEGMENTO_Y03_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Lote de serviço", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº sequencial do registro no lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'Y' = dados opcionais; o tipo vem nas posições 18-19 (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Código de movimento Remessa", 16, 17,
     "Código de movimento: com o Segmento Y-03, só '01' Entrada de boleto; outro código recusa o boleto por segmento inválido (ver MOVIMENTO_REMESSA_CODES, nota 14)."),
    ("Identificação Registro", 18, 19,
     "'03' = dados do QR Code Pix (Boleto SX), junto com os Segmentos P e Q da entrada. Só vale para a carteira '5' com forma de cadastramento '1' (Rápida com Registro, boleto impresso pelo Beneficiário) (nota 42)."),
    ("Uso Reservado (Filler)", 20, 80,
     "Reservado para uso do Banco (61 posições); preenchido com brancos."),
    ("Tipo de Chave Pix", 81, 81,
     "Tipo da chave Pix que o Beneficiário cadastrou no Santander: '1' CPF, '2' CNPJ, '3' celular, '4' e-mail, '5' EVP (chave aleatória) (nota 49)."),
    ("Chave Pix", 82, 158,
     "Chave Pix cadastrada no banco, que identifica o Beneficiário e a conta que recebe os créditos. Sem uma chave válida para receber Pix não há QR Code (nota 50)."),
    ("Código identificação do QR Code", 159, 193,
     "Identificador do QR Code (TXID), opcional: único por boleto, de 26 a 35 caracteres, só letras e números, sem brancos. Com menos de 26, o boleto é registrado sem QR Code (ocorrência P2); repetido na mesma remessa, só um boleto leva o QR Code, e em remessas diferentes o boleto é rejeitado. Em branco, o banco gera o TXID (nota 52)."),
    ("Uso Reservado (Filler)", 194, 240,
     "Reservado para uso do Banco (47 posições); preenchido com brancos."),
]

# SEGMENTO_Y53_REMESSA_FIELDS
SEGMENTO_Y53_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Lote de serviço", 4, 7,
     "Número do lote: '0001' no primeiro lote do arquivo e mais 1 a cada lote seguinte, sem repetir no arquivo (o Header de Arquivo usa '0000' e o Trailer de Arquivo '9999') (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '3' = Detalhe. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Nº sequencial do registro no lote", 9, 13,
     "Número do registro dentro do lote, começando em 1 e crescente, sem repetir. Junto com o número do lote, controla os documentos do lote (nota 11)."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Segmento do registro detalhe: 'Y' = dados opcionais; o tipo vem nas posições 18-19 (nota 13)."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Código de movimento Remessa", 16, 17,
     "Código de movimento da remessa, o mesmo do Segmento P do boleto: é por ele e pelo número do registro que o banco junta os segmentos de um mesmo boleto. Tabela em MOVIMENTO_REMESSA_CODES (nota 14)."),
    ("Identificação Registro", 18, 19,
     "'53' = tipo de pagamento aceito para o boleto (nota 42)."),
    ("Identificação de tipo de Pagamento", 20, 21,
     "Tipo de pagamento: '01' aceita qualquer valor; '02' entre o mínimo e o máximo; '03' não aceita pagamento com valor divergente (nota 46)."),
    ("Quantidade de Pagamentos", 22, 23,
     "Quantidade de pagamentos possíveis: de 01 a 99 com o tipo de pagamento '02'; com os tipos '01' e '03', informe '00' (nota 47)."),
    ("Tipo de valor Informado", 24, 24,
     "Como ler o valor máximo (posições 25-39): '1' = percentual, '2' = valor. Não se aplica ao tipo de pagamento '03' (nota 48)."),
    ("Valor Máximo ou Percentual Máximo", 25, 39,
     "Valor máximo (13 inteiros + 2 decimais) ou percentual máximo (10 inteiros + 5 decimais) aceito no pagamento, conforme o tipo de valor na posição 24, sem vírgula (nota 48)."),
    ("Tipo de valor Informado", 40, 40,
     "Como ler o valor mínimo (posições 41-55): '1' = percentual, '2' = valor. Não se aplica ao tipo de pagamento '03' (nota 48)."),
    ("Valor Mínimo ou Percentual Mínimo", 41, 55,
     "Valor mínimo (13 inteiros + 2 decimais) ou percentual mínimo (10 inteiros + 5 decimais) aceito no pagamento, conforme o tipo de valor na posição 40, sem vírgula (nota 48)."),
    ("Uso Reservado (Filler)", 56, 240,
     "Reservado para uso do Banco (185 posições); preenchido com brancos."),
]

# TRAILER_LOTE_REMESSA_FIELDS
TRAILER_LOTE_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 353 / 008 / 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 5; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros do lote", 18, 23,
     "Numérico, 6 posições; ver nota 37 do manual."),
    ("Uso Reservado (Filler)", 24, 240,
     "Reservado para uso do Banco (217 posições); conteúdo no manual: Brancos."),
]

# TRAILER_ARQUIVO_REMESSA_FIELDS
TRAILER_ARQUIVO_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 9; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de lotes do arquivo", 18, 23,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=1."),
    ("Quantidade de registros do arquivo", 24, 29,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=0+1+2+3+5+9."),
    ("Uso Reservado (Filler)", 30, 240,
     "Reservado para uso do Banco (211 posições); conteúdo no manual: Brancos."),
]

# --- Retorno ----------------------------------------------------------------------------------

# HEADER_ARQUIVO_RETORNO_FIELDS
HEADER_ARQUIVO_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Lote de serviço", 4, 7,
     "Lote de serviço: '0000' no Header de Arquivo (nota 1)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '0' = Header de Arquivo. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Uso Reservado (Filler)", 9, 16,
     "Reservado para uso do Banco (8 posições); preenchido com brancos."),
    ("Tipo de inscrição da empresa", 17, 17,
     "Tipo do documento da empresa (o Beneficiário): '1' = CPF, '2' = CNPJ."),
    ("Inscrição da empresa", 18, 32,
     "CPF ou CNPJ da empresa, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 54)."),
    ("Agência do Beneficiário", 33, 36,
     "Agência do Beneficiário, sem o dígito. No retorno, agência e conta vêm no trecho que na remessa guarda o código de transmissão (nota 3)."),
    ("Dígito da Agência do Beneficiário", 37, 37,
     "Dígito da agência do Beneficiário (nota 3)."),
    ("Número da conta corrente", 38, 46,
     "Conta corrente do Beneficiário, 9 posições, sem o dígito (nota 3)."),
    ("Dígito verificador da conta", 47, 47,
     "Dígito verificador da conta corrente do Beneficiário (nota 3)."),
    ("Uso Reservado (Filler)", 48, 52,
     "Reservado para uso do Banco (5 posições); preenchido com brancos."),
    ("Código do Beneficiário", 53, 61,
     "Código do Beneficiário no Santander."),
    ("Uso Reservado (Filler)", 62, 72,
     "Reservado para uso do Banco (11 posições); preenchido com brancos."),
    ("Nome da empresa", 73, 102,
     "Nome da empresa beneficiária."),
    ("Nome do Banco", 103, 132,
     "Texto 'BANCO SANTANDER', o nome do banco."),
    ("Uso Reservado (Filler)", 133, 142,
     "Reservado para uso do Banco (10 posições); preenchido com brancos."),
    ("Código remessa / retorno", 143, 143,
     "'2' = arquivo de retorno, enviado pelo banco ao Beneficiário (na remessa é '1')."),
    ("Data de geração do arquivo", 144, 151,
     "Data em que o banco gerou o arquivo de retorno, no formato DDMMAAAA."),
    ("Uso Reservado (Filler)", 152, 157,
     "Reservado para uso do Banco (6 posições); preenchido com brancos."),
    ("Nº seqüencial do arquivo", 158, 163,
     "Número sequencial do arquivo de retorno: aumenta 1 a cada arquivo (nota 4)."),
    ("Nº da versão do layout do arquivo", 164, 166,
     "Versão do layout do arquivo: '040'."),
    ("Uso Reservado (Filler)", 167, 240,
     "Reservado para uso do Banco (74 posições); preenchido com brancos."),
]

# HEADER_LOTE_RETORNO_FIELDS
HEADER_LOTE_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Código do Santander na compensação: '033'."),
    ("Número do lote retorno", 4, 7,
     "Número do lote de retorno. É sequencial para todos os beneficiários do mesmo layout: o lote 5207 indica que 5206 beneficiários receberam arquivo antes deste (notas 1 e 11)."),
    ("Tipo de registro", 8, 8,
     "Tipo do registro: '1' = Header de Lote. Os tipos são 0 Header de Arquivo, 1 Header de Lote, 3 Detalhe, 5 Trailer de Lote e 9 Trailer de Arquivo (nota 2)."),
    ("Tipo de operação", 9, 9,
     "Tipo de operação: 'T' no retorno (na remessa é 'R')."),
    ("Tipo de serviço", 10, 11,
     "Tipo de serviço: '01' = Cobrança."),
    ("Uso Reservado (Filler)", 12, 13,
     "Reservado para uso do Banco (2 posições); preenchido com brancos."),
    ("Nº da versão do layout do lote", 14, 16,
     "Versão do layout do lote: '040' no retorno (na remessa o manual indica '030')."),
    ("Uso Reservado (Filler)", 17, 17,
     "Reservado para uso do Banco (1 posições); preenchido com brancos."),
    ("Tipo de inscrição da empresa", 18, 18,
     "Tipo do documento da empresa (o Beneficiário): '1' = CPF, '2' = CNPJ."),
    ("Inscrição da empresa", 19, 33,
     "CPF ou CNPJ da empresa, alinhado à direita e completado com zeros à esquerda. O campo é alfanumérico porque o CNPJ alfanumérico da Receita Federal passa a ser atribuído a novas empresas a partir de julho de 2026 (nota 54)."),
    ("Código do Beneficiário", 34, 42,
     "Código do Beneficiário no Santander."),
    ("Uso Reservado (Filler)", 43, 53,
     "Reservado para uso do Banco (11 posições)."),
    ("Agência do Beneficiário", 54, 57,
     "Agência do Beneficiário, sem o dígito. No retorno, agência e conta vêm no trecho que na remessa guarda o código de transmissão (nota 3)."),
    ("Dígito da Agência do Beneficiário", 58, 58,
     "Dígito da agência do Beneficiário (nota 3)."),
    ("Número da conta do Beneficiário", 59, 67,
     "Conta corrente do Beneficiário, 9 posições, sem o dígito (nota 3)."),
    ("Dígito verificador da conta", 68, 68,
     "Dígito verificador da conta corrente do Beneficiário (nota 3)."),
    ("Uso Reservado (Filler)", 69, 73,
     "Reservado para uso do Banco (5 posições)."),
    ("Nome da empresa", 74, 103,
     "Nome da empresa beneficiária."),
    ("Uso Reservado (Filler)", 104, 183,
     "Reservado para uso do Banco (80 posições)."),
    ("Número do Retorno", 184, 191,
     "Número do retorno: identifica a sequência de devolução dos arquivos entre o banco e o Beneficiário (nota 10)."),
    ("Data da gravação remessa/retorno", 192, 199,
     "Data da gravação do retorno, no formato DDMMAAAA."),
    ("Uso Reservado (Filler)", 200, 240,
     "Reservado para uso do Banco (41 posições); preenchido com brancos."),
]

# SEGMENTO_T_RETORNO_FIELDS
SEGMENTO_T_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote retorno", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº sequencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: T; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de Movimento (Ocorrência)", 16, 17,
     "Código de movimento de retorno (evento ocorrido com o boleto): 02 Entrada confirmada; 03 Entrada rejeitada; 04 transferência para carteira Simples; 05 transferência para carteira Desconto/Penhor/Vendor/FIDC/Cessão; 06 Liquidação do Boleto Efetivada; 08 Confirmação do Recebimento do Cancelamento do Desconto; 09 Baixa; 11 boletos em carteira (em ser); 12 confirmação recebimento instrução de abatimento; 13 confirmação recebimento instrução de cancelamento abatimento; 14 confirmação recebimento instrução alteração de vencimento; 17 liquidação após baixa ou liquidação boleto não registrado; ... Tabela completa em MOVIMENTO_RETORNO_CODES (nota 40 do manual)."),
    ("Agência do Beneficiário", 18, 21,
     "Numérico, 4 posições; ver nota 3 do manual."),
    ("Dígito da Agência do Beneficiário", 22, 22,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Número da conta corrente", 23, 31,
     "Numérico, 9 posições; ver nota 3 do manual."),
    ("Dígito verificador da conta", 32, 32,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Uso Reservado (Filler)", 33, 40,
     "Reservado para uso do Banco (8 posições); conteúdo no manual: Brancos."),
    ("Nosso Número (Identificação do boleto no Banco)", 41, 53,
     "Numérico, 13 posições; conteúdo no manual: Nosso número; ver nota 15 do manual."),
    ("Código da carteira", 54, 54,
     "Alfanumérico, 1 posição; ver nota 5 do manual."),
    ("Número do Documento (Seu Número)", 55, 69,
     "Alfanumérico, 15 posições; conteúdo no manual: Seu número; ver nota 16 do manual."),
    ("Data de Vencimento do boleto", 70, 77,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Valor nominal do boleto", 78, 92,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Nº do Banco Cobrador / Recebedor", 93, 95,
     "Numérico, 3 posições."),
    ("Agência Cobradora / Recebedora", 96, 99,
     "Numérico, 4 posições; ver nota 53 do manual."),
    ("Dígito da Agência do Beneficiário", 100, 100,
     "Numérico, 1 posição."),
    ("Identif. do boleto na empresa", 101, 125,
     "Alfanumérico, 25 posições; conteúdo no manual: Uso Beneficiário (opcional); ver nota 24 do manual."),
    ("Código da moeda", 126, 127,
     "Numérico, 2 posições; ver nota 26 do manual."),
    ("Tipo de inscrição Pagador", 128, 128,
     "Numérico, 1 posição; conteúdo no manual: 1 =CPF, 2 = CNPJ; ver nota 29 do manual."),
    ("Inscrição Pagador", 129, 143,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Nome do Pagador", 144, 183,
     "Alfanumérico, 40 posições."),
    ("Conta Cobrança", 184, 193,
     "Alfanumérico, 10 posições."),
    ("Valor da Tarifa/Custas", 194, 208,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador."),
    ("Identificação para rejeições, tarifas, custas, liquidações, baixas e PIX.", 209, 218,
     "Alfanumérico, 10 posições; conteúdo no manual: ocorre 5 vezes; cada ocorrência ocupa 2 dígitos; ver nota 40-A e 40-C do manual."),
    ("Uso Reservado (Filler)", 219, 240,
     "Reservado para uso do Banco (22 posições)."),
]

# SEGMENTO_U_RETORNO_FIELDS
SEGMENTO_U_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: U; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de Movimento (Ocorrência)", 16, 17,
     "Código de movimento de retorno, o mesmo do Segmento T do título. Tabela em MOVIMENTO_RETORNO_CODES (nota 40 do manual)."),
    ("Juros / Multa / Encargos", 18, 32,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor do desconto concedido", 33, 47,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor do Abatimento Concedido/Cancelado", 48, 62,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor do IOF recolhido", 63, 77,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor Pago pelo Pagador", 78, 92,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor liquido a ser creditado", 93, 107,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor de outras despesas", 108, 122,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor de outros créditos", 123, 137,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Data da ocorrência", 138, 145,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Data da efetivação do crédito", 146, 153,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Código da ocorrência do Pagador", 154, 157,
     "Numérico, 4 posições; ver nota 41 do manual."),
    ("Data da ocorrência do Pagador", 158, 165,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Valor da ocorrência do Pagador", 166, 180,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Complemento da ocorrência do Pagador", 181, 210,
     "Alfanumérico, 30 posições; ver nota 41 do manual."),
    ("Código do Banco correspondente na compensação", 211, 213,
     "Numérico, 3 posições; ver nota 31 do manual."),
    ("Uso Reservado (Filler)", 214, 240,
     "Reservado para uso do Banco (27 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_Y03_RETORNO_FIELDS
SEGMENTO_Y03_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº sequencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: Y; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de Movimento (Ocorrência)", 16, 17,
     "Numérico, 2 posições; ver nota 14 do manual."),
    ("Identificação Registro", 18, 19,
     "Numérico, 2 posições; conteúdo no manual: 03; ver nota 42 do manual."),
    ("Uso Reservado (Filler)", 20, 80,
     "Reservado para uso do Banco (61 posições); conteúdo no manual: Brancos."),
    ("Tipo de Chave Pix / Brancos", 81, 81,
     "Alfanumérico, 1 posição; ver nota 49 do manual."),
    ("Chave Pix / URL do QR Code", 82, 158,
     "Alfanumérico, 77 posições; ver nota 50 do manual."),
    ("Código identificação do QR Code", 159, 193,
     "Alfanumérico, 35 posições; ver nota 52 do manual."),
    ("Uso Reservado (Filler)", 194, 240,
     "Reservado para uso do Banco (47 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_Y04_RETORNO_FIELDS
SEGMENTO_Y04_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: Y; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de Movimento (Ocorrência)", 16, 17,
     "Numérico, 2 posições; conteúdo no manual: 06; ver nota 40 do manual."),
    ("Identificação Registro Opcional", 18, 19,
     "Numérico, 2 posições; conteúdo no manual: 04; ver nota 42 do manual."),
    ("Identificação do Cheque 1", 20, 53,
     "Alfanumérico, 34 posições; ver nota 43 do manual."),
    ("Identificação do Cheque 2", 54, 87,
     "Alfanumérico, 34 posições; ver nota 43 do manual."),
    ("Identificação do Cheque 3", 88, 121,
     "Alfanumérico, 34 posições; ver nota 43 do manual."),
    ("Identificação do Cheque 4", 122, 155,
     "Alfanumérico, 34 posições; ver nota 43 do manual."),
    ("Identificação do Cheque 5", 156, 189,
     "Alfanumérico, 34 posições; ver nota 43 do manual."),
    ("Identificação do Cheque 6", 190, 223,
     "Alfanumérico, 34 posições; ver nota 43 do manual."),
    ("Uso Reservado (Filler)", 224, 240,
     "Reservado para uso do Banco (17 posições); conteúdo no manual: Brancos."),
]

# TRAILER_LOTE_RETORNO_FIELDS
TRAILER_LOTE_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 5; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros do lote", 18, 23,
     "Numérico, 6 posições; ver nota 37 do manual."),
    ("Quantidade de Boletos cobrança simples", 24, 29,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos cobrança simples", 30, 46,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Quantidade de Boletos em cobrança vinculada", 47, 52,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos em cobrança vinculada", 53, 69,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Quantidade de Boletos em cobrança caucionada", 70, 75,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos em cobrança caucionada", 76, 92,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Quantidade de Boletos em cobrança descontada", 93, 98,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos em cobrança descontada", 99, 115,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Número do aviso de lançamento", 116, 123,
     "Alfanumérico, 8 posições; ver nota 39 do manual."),
    ("Uso Reservado (Filler)", 124, 240,
     "Reservado para uso do Banco (117 posições); conteúdo no manual: Brancos."),
]

# TRAILER_ARQUIVO_RETORNO_FIELDS
TRAILER_ARQUIVO_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 9; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de lotes do arquivo", 18, 23,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=1."),
    ("Quantidade de registros do arquivo", 24, 29,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=0+1+3+5+9."),
    ("Uso Reservado (Filler)", 30, 240,
     "Reservado para uso do Banco (211 posições); conteúdo no manual: Brancos."),
]

# --- Mapas por segmento e tipo de registro --------------------------------------------------------

SEGMENTOS = {
    ("Remessa", "P"): SEGMENTO_P_REMESSA_FIELDS,
    ("Remessa", "Q"): SEGMENTO_Q_REMESSA_FIELDS,
    ("Remessa", "R"): SEGMENTO_R_REMESSA_FIELDS,
    ("Remessa", "S-1"): SEGMENTO_S_1_REMESSA_FIELDS,
    ("Remessa", "S-2"): SEGMENTO_S_2_REMESSA_FIELDS,
    ("Retorno", "T"): SEGMENTO_T_RETORNO_FIELDS,
    ("Retorno", "U"): SEGMENTO_U_RETORNO_FIELDS,
    ("Remessa", "Y-03"): SEGMENTO_Y03_REMESSA_FIELDS,
    ("Remessa", "Y-53"): SEGMENTO_Y53_REMESSA_FIELDS,
    ("Retorno", "Y-03"): SEGMENTO_Y03_RETORNO_FIELDS,
    ("Retorno", "Y-04"): SEGMENTO_Y04_RETORNO_FIELDS,
}

REGISTROS = {
    ("Remessa", "0"): HEADER_ARQUIVO_REMESSA_FIELDS,
    ("Retorno", "0"): HEADER_ARQUIVO_RETORNO_FIELDS,
    ("Remessa", "1"): HEADER_LOTE_REMESSA_FIELDS,
    ("Retorno", "1"): HEADER_LOTE_RETORNO_FIELDS,
    ("Remessa", "5"): TRAILER_LOTE_REMESSA_FIELDS,
    ("Retorno", "5"): TRAILER_LOTE_RETORNO_FIELDS,
    ("Remessa", "9"): TRAILER_ARQUIVO_REMESSA_FIELDS,
    ("Retorno", "9"): TRAILER_ARQUIVO_RETORNO_FIELDS,
}

# --- Tabelas de código ------------------------------------------------------------------------

MOVIMENTO_REMESSA_CODES = {  # nota 14: código de movimento da remessa (posições 16-17 dos Segmentos P, Q, R e S)
    "01": "Entrada de boleto",
    "02": "Pedido de baixa",
    "04": "Concessão de abatimento",
    "05": "Cancelamento de abatimento",
    "06": "Alteração de vencimento",
    "07": "Alteração da identificação do boleto na empresa (Controle Participante)",
    "08": "Alteração seu número",
    "09": "Pedido de Protesto",
    "18": "Pedido de Sustação de Protesto",
    "10": "Concessão de Desconto",
    "11": "Cancelamento de desconto",
    "12": "Transferência de Titularidade automática",
    "15": "Transferência da carteira Simples para a carteira Cessão",
    "16": "Baixa de Cessão por Descaracterização",
    "17": "Baixa de Cessão por Pagamento",
    "31": "Alteração de outros dados",
    "47": "Alteração do Valor Nominal do boleto",
    "48": "Alteração do Valor Mínimo ou Percentual Mínimo",
    "49": "Alteração do Valor Máximo ou Percentual Máximo",
    "98": "Não Protestar (Antes de iniciar o ciclo de protesto )",
}

MOVIMENTO_RETORNO_CODES = {  # nota 40: código de movimento do retorno (posições 16-17 dos Segmentos T e U)
    "02": "Entrada confirmada",
    "03": "Entrada rejeitada",
    "04": "transferência para carteira Simples",
    "05": "transferência para carteira Desconto/Penhor/Vendor/FIDC/Cessão",
    "06": "Liquidação do Boleto Efetivada",
    "08": "Confirmação do Recebimento do Cancelamento do Desconto",
    "09": "Baixa",
    "11": "boletos em carteira (em ser)",
    "12": "confirmação recebimento instrução de abatimento",
    "13": "confirmação recebimento instrução de cancelamento abatimento",
    "14": "confirmação recebimento instrução alteração de vencimento",
    "17": "liquidação após baixa ou liquidação boleto não registrado",
    "19": "confirmação recebimento instrução de protesto",
    "20": "confirmação recebimento instrução de sustação/Não Protestar",
    "23": "remessa a cartório (aponte em cartório)",
    "24": "retirada de cartorio e manutenção em carteira",
    "25": "protestado e baixado (baixa por ter sido protestado)",
    "26": "instrução rejeitada",
    "27": "confirmação do pedido de alteração de outros dados",
    "28": "débito de tarifas/custas",
    "29": "ocorrências do Pagador",
    "30": "alteração de dados rejeitada",
    "32": "Código de IOF inválido",
    "51": "Boleto DDA reconhecido pelo Pagador",
    "52": "Boleto DDA não reconhecido pelo Pagador",
    "53": "Boleto DDA recusado pela PCR",
    "61": "Confirmação de Alteração do Valor Nominal do Boleto",
    "91": "Confirmação de Alteração do Valor Mínimo ou Percentual Mínimo",
    "92": "Confirmação de Alteração do Valor Máximo ou Percentual Máximo",
    "93": "Pagamento do Boleto Recebido",
    "94": "Cancelamento do Pagamento Recebido",
    "A4": "Pagador DDA",
}

ESPECIE_BOLETO_CODES = {  # nota 20: espécie do boleto (posições 107-108 do Segmento P)
    "02": "DM - DUPLICATA MERCANTIL",
    "04": "DS - DUPLICATA DE SERVICO",
    "07": "LC - LETRA DE CÂMBIO (SOMENTE PARA BANCO 353)",
    "30": "LC - LETRA DE CÂMBIO (SOMENTE PARA BANCO 008)",
    "12": "NP - NOTA PROMISSORIA",
    "13": "NR - NOTA PROMISSORIA RURAL",
    "17": "RC - RECIBO",
    "20": "AP – APOLICE DE SEGURO",
    "31": "BCC – CARTÃO DE CRÉDITO",
    "32": "BDP – BOLETO DE PROPOSTA",
    "33": "BDA – BOLETO DE DEPOSITO E APORTE",
    "97": "CH – CHEQUE",
    "98": "ND - NOTA PROMISSORIA DIRETA",
}

REJEICAO_CODES = {  # nota 40-A: rejeições associadas aos movimentos 03, 26 e 30 (Segmento T, posições 209-218)
    "01": "código do banco invalido",
    "02": "código do registro detalhe inválido",
    "03": "código do segmento invalido",
    "04": "código do movimento não permitido para carteira",
    "05": "código de movimento invalido",
    "06": "tipo/numero de inscrição do Beneficiário inválidos",
    "07": "agencia/conta/DV invalido",
    "08": "nosso numero invalido",
    "09": "nosso numero duplicado",
    "10": "carteira invalida",
    "11": "forma de cadastramento do boleto invalida Se Desconto ou Cessão, boleto rejeitado - operação de Desconto ou Cessão fora do horário limite.",
    "12": "tipo de documento invalido",
    "13": "identificação da emissão do Boleto invalida",
    "14": "identificação da distribuição do Boleto invalida",
    "15": "características da cobrança incompatíveis",
    "16": "data de vencimento invalida",
    "17": "data de vencimento anterior a data de emissão",
    "18": "vencimento fora do prazo de operação",
    "19": "boleto a cargo de bancos correspondentes com vencimento inferior a xx dias",
    "20": "valor do boleto invalido",
    "21": "espécie do boleto invalida",
    "22": "espécie não permitida para a carteira",
    "23": "aceite invalido",
    "24": "Data de emissão inválida",
    "25": "Data de emissão posterior a data de entrada",
    "26": "Código de juros de mora inválido",
    "27": "Valor/Taxa de juros de mora inválido",
    "28": "Código de desconto inválido",
    "29": "Valor do desconto maior ou igual ao valor do boleto",
    "30": "Desconto a conceder não confere",
    "31": "Concessão de desconto - já existe desconto anterior",
    "32": "Valor do IOF",
    "33": "Valor do abatimento inválido",
    "34": "Valor do abatimento maior ou igual ao valor do boleto",
    "35": "Abatimento a conceder não confere",
    "36": "Concessão de abatimento - já existe abatimento anterior",
    "37": "Código para protesto inválido",
    "38": "Prazo para protesto inválido",
    "39": "Pedido de protesto não permitido para o boleto",
    "40": "Boleto com ordem de protesto emitida",
    "41": "Pedido de cancelamento/sustação para boletos sem instrução de protesto",
    "42": "Código para baixa/devolução inválido",
    "43": "Prazo para baixa/devolução inválido",
    "44": "Boleto já baixado",
    "45": "Nome do Pagador não informado",
    "46": "Tipo /Número de inscrição do Pagador inválidos",
    "47": "Endereço do Pagador não informado",
    "48": "CEP inválido",
    "49": "CEP sem praça de cobrança (não localizado)",
    "50": "CEP referente a um Banco Correspondente",
    "51": "CEP incompatível com a unidade de federação",
    "52": "Unidade de federação inválida",
    "53": "Tipo/Número de inscrição do sacador/avalista inválidos",
    "54": "Sacador/Avalista não informado",
    "55": "Nosso número no Banco Correspondente não informado",
    "56": "Código do Banco Correspondente não informado",
    "57": "Código da multa inválido",
    "58": "Data da multa inválida",
    "59": "Valor/Percentual da multa inválido",
    "60": "Movimento para boleto não cadastrado",
    "61": "Alteração de agência cobradora/dv inválida",
    "62": "Tipo de impressão inválido",
    "63": "Entrada para boleto já cadastrado",
    "64": "Número da linha inválido",
    "65": "A espécie de boleto não permite a instrução",
    "72": "Entrada de boleto Sem Registro",
    "90": "Identificador/Quantidade de Parcelas de carnê invalido",
    "91": "Boleto Descontado, instrução não permitida",
    "92": "Data de Desconto Inválida",
    "93": "Número do lote remessa inválido",
    "B2": "Valor Nominal do Boleto Conflitante",
    "B3": "Tipo de Pagamento Inválido",
    "B4": "Valor Máximo ou Percentual Máximo Inválido",
    "B5": "Valor Mínimo ou Percentual Mínimo Inválido",
    "C1": "Não foi realizada a contratação do produto SX Integra para operar com Cessão",
    "C2": "Operação de Cessão não Confirmada",
    "C3": "Operação de Cessão Rejeitada – Ver detalhes no relatório do SX Integra",
    "E1": "CNPJ Raiz do pagador não pode ser igual ao do beneficiário original",
    "E2": "CNPJ Raiz do pagador não pode ser igual ao do beneficiário final",
    "E3": "CNPJ Raiz do beneficiário final não pode ser igual ao CNPJ Raiz do beneficiário original para o convênio",
    "E4": "CPF do pagador não pode ser igual ao do beneficiário original",
    "E5": "CPF do pagador não pode ser igual ao do beneficiário final",
    "E6": "CPF do beneficiário final não pode ser igual ao CPF do beneficiário original para o convênio",
    "E7": "Registro não permitido – Beneficiário Final com restrição",
    "E8": "Código de Moeda Inválido",
    "E9": "Obrigatório informar o Beneficiário Final para o boleto",
    "P1": "Registrado com QR Code Pix",
    "P2": "Registrado sem QR Code Pix",
    "P3": "Chave PIX Inválida",
    "P4": "Chave PIX sem cadastro na DICT",
    "P5": "Chave PIX não é compatível com o CNPJ",
    "P6": "Identificador (TXID) em duplicidade",
    "P7": "Identificador (TXID) inválido ou não encontrado",
    "P8": "Alteração não permitida – QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "P9": "Cancelamento não permitido – QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "Z1": "Quantidade de Pagamento Possíveis Inválido",
    "Z5": "Boleto com reserva, instrução não permitida",
    "Z6": "Segmento Inválido para o tipo de Carteira de Cobrança",
    "Z7": "Instrução exige segmento Y53",
    "Z8": "Instrução recusada - limite de alt.de vencto atingido p/ boletos em garantia",
    "Z9": "Instrução recusada pelo sistema de garantias",
    "B6": "Instrução recusada, convenio com garantia em conta Escrow",
    "A1": "Instrução recusada – Pix Automático",
}

LIQUIDACAO_CODES = {  # nota 40-C: origem da liquidação, com os movimentos 06, 17 e 93 (Segmento T, posições 209-218)
    "01": "Por saldo",
    "02": "Por conta",
    "03": "No próprio banco",
    "04": "Compensação eletrônica",
    "05": "Compensação convencional",
    "06": "Arquivo magnético",
    "07": "Após feriado local",
    "08": "Em cartório",
    "09": "Pagamento Parcial",
    "61": "Liquidação por pagamento PIX",
}

BAIXA_CODES = {  # nota 40-C: origem da baixa, com os movimentos 09 e 94 (Segmento T, posições 209-218)
    "09": "Comandada banco",
    "10": "Comandada cliente arquivo",
    "11": "Comandada cliente on-line",
    "12": "Decurso prazo - cliente",
    "13": "Decurso prazo - banco",
    "92": "Baixa por pagamento PIX",
    "93": "Pagamento do boleto recebido",
    "94": "Cancelamento do pagamento recebido",
}
