# -*- coding: utf-8 -*-
"""
CNAB 400 Santander (banco 033; o Header também aceita 353, código legado) - Cobrança - referência de campos.

Fonte: "Layout Cobrança H7800 - CNAB 353/400 posições - padrão Santander", versão 2.37, fevereiro/2026
(manual oficial do Banco Santander, https://www.santander.com.br/layout-de-arquivos). As notas citadas
nas descrições são as notas desse manual.

Registros (posição 1 da linha):
  Remessa: 0 Header; 1 Movimento; 8 Tipo de pagamento e dados de QR Code/PIX (opcional, Boleto SX);
           2 Mensagem no Recibo do Pagador e 4/5/6/7 Mensagem na Ficha de Compensação (opcionais); 9 Trailer.
  Retorno: 0 Header; 1 Movimento; 2 Dados de QR Code/PIX (opcional); 9 Trailer.

Convenções de nome (a interface depende delas): o resumo da grade procura por trechos como "Data de
Vencimento", "Valor Nominal", "Nosso Número", "Número do Documento", "Código de Movimento" e "Nome do
Pagador"; "Valor Pago" é o valor liquidado no retorno; campos reservados levam "Uso Reservado (Filler)" e
aparecem acinzentados. Por isso alguns títulos trazem, entre parênteses, o nome que o manual usa.

Inconsistências do próprio manual, mantidas como estão até conferir com arquivo real: no registro 8 os
percentuais (020-024 e 038-042) ocupam 5 posições mas declaram tamanho 3; no Movimento de retorno o
"Complemento" (384-385) declara tamanho 1 para 2 posições. Os tamanhos aqui seguem as posições.
"""

# --- Remessa ----------------------------------------------------------------------------------

# Header Remessa
HEADER_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Numérico, 1 posição; ver nota 0 do manual."),
    ("Código da Remessa", 2, 2,
     "Numérico, 1 posição; ver nota 1 do manual."),
    ("Literal de Transmissão", 3, 9,
     "Alfanumérico, 7 posições; conteúdo no manual: REMESSA."),
    ("Código do Tipo Serviço", 10, 11,
     "Numérico, 2 posições; ver nota 01 do manual."),
    ("Literal de Serviço", 12, 26,
     "Alfanumérico, 15 posições; conteúdo no manual: COBRANCA."),
    ("Código de Transmissão", 27, 46,
     "Numérico, 20 posições; ver nota 1 do manual."),
    ("Nome do Beneficiário", 47, 76,
     "Alfanumérico, 30 posições."),
    ("Código do Banco", 77, 79,
     "Numérico, 3 posições; conteúdo no manual: 353/033."),
    ("Nome do Banco", 80, 94,
     "Alfanumérico, 15 posições; conteúdo no manual: SANTANDER."),
    ("Data da Geração do Arquivo", 95, 100,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA."),
    ("Uso Reservado (Filler)", 101, 116,
     "Reservado para uso do Banco (16 posições); conteúdo no manual: Zeros."),
    ("Mensagem 1", 117, 163,
     "Alfanumérico, 47 posições."),
    ("Mensagem 2", 164, 210,
     "Alfanumérico, 47 posições."),
    ("Mensagem 3", 211, 257,
     "Alfanumérico, 47 posições."),
    ("Mensagem 4", 258, 304,
     "Alfanumérico, 47 posições."),
    ("Mensagem 5", 305, 351,
     "Alfanumérico, 47 posições."),
    ("Uso Reservado (Filler)", 352, 385,
     "Reservado para uso do Banco (34 posições); conteúdo no manual: Brancos."),
    ("Uso Reservado (Filler)", 386, 391,
     "Reservado para uso do Banco (6 posições); conteúdo no manual: Brancos."),
    ("Nº sequencial do arquivo", 392, 394,
     "Numérico, 3 posições; conteúdo no manual: Opcional; ver nota 32 do manual."),
    ("Nº sequencial do registro no arquivo", 395, 400,
     "Numérico, 6 posições; conteúdo no manual: 000001."),
]

# Detail Remessa
DETAIL_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Numérico, 1 posição; ver nota 1 do manual."),
    ("Tipo de inscrição do beneficiário", 2, 3,
     "Numérico, 2 posições; conteúdo no manual: 01 = CPF, 02 = CNPJ."),
    ("Inscrição do beneficiário", 4, 17,
     "Alfanumérico, 14 posições; ver nota 38 do manual."),
    ("Código da agência beneficiário", 18, 21,
     "Numérico, 4 posições; ver nota 2 do manual."),
    ("Conta movimento beneficiário", 22, 29,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Conta cobrança beneficiário", 30, 37,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Identificação do boleto na empresa", 38, 62,
     "Alfanumérico, 25 posições; conteúdo no manual: Opcional; ver nota 19 do manual."),
    ("Nosso Número (Identificação do boleto no banco)", 63, 70,
     "Numérico, 8 posições; conteúdo no manual: Nosso Número; ver nota 3 do manual."),
    ("Data do desconto 2", 71, 76,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA; ver nota 11 do manual."),
    ("Uso Reservado (Filler)", 77, 77,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Branco."),
    ("Código de Multa", 78, 78,
     "Numérico, 1 posição; ver nota 4 do manual."),
    ("Percentual de Multa", 79, 82,
     "Numérico, 4 posições; 2 casas decimais, sem separador; conteúdo no manual: Dec. sem separador."),
    ("Código da Moeda", 83, 84,
     "Numérico, 2 posições; ver nota 00 do manual."),
    ("Valor do boleto em outra unidade", 85, 97,
     "Numérico, 13 posições; 5 casas decimais, sem separador; conteúdo no manual: Não se aplica."),
    ("Uso Reservado (Filler)", 98, 101,
     "Reservado para uso do Banco (4 posições); conteúdo no manual: Brancos."),
    ("Data da Multa", 102, 107,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA; ver nota 4 do manual."),
    ("Tipo de Cobrança (Código da Carteira)", 108, 108,
     "Numérico, 1 posição; conteúdo no manual: Código da Carteira; ver nota 20 do manual."),
    ("Código de Movimento Remessa (Código da Ocorrência)", 109, 110,
     "Código de movimento da remessa (instrução comandada pelo Beneficiário): 01 Entrada do boleto; 02 Baixa do boleto; 04 Concessão de abatimento; 05 Cancelamento do abatimento; 06 Alteração do vencimento; 07 Alteração do número controle beneficiário; 08 Alteração do Seu Número; 09 Protestar; 15 Transferência da carteira Simples para Cessão; 16 Baixa de Cessão por Descaracterização; 17 Baixa de Cessão por Pagamento; 18 Sustar o protesto (Após início do ciclo de protesto); 47 Alteração do valor nominal do boleto; 48 Alteração do valor mínimo/percentual; 49 Alteração do valor máximo/percentual. Tabela em COMANDO_REMESSA_CODES (nota 21 do manual)."),
    ("Número do Documento (Seu Número)", 111, 120,
     "Alfanumérico, 10 posições; conteúdo no manual: Seu Número; ver nota 22 do manual."),
    ("Data de vencimento do boleto", 121, 126,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA; ver nota 7 do manual."),
    ("Valor nominal do boleto", 127, 139,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Número do banco cobrador", 140, 142,
     "Numérico, 3 posições; conteúdo no manual: 353/033."),
    ("Código agência Cobradora", 143, 147,
     "Numérico, 5 posições; ver nota 23 do manual."),
    ("Espécie do boleto", 148, 149,
     "Numérico, 2 posições; ver nota 24 do manual."),
    ("Identificação boleto aceite / não aceite", 150, 150,
     "Alfanumérico, 1 posição; conteúdo no manual: N= Não aceite."),
    ("Data de emissão do boleto", 151, 156,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA; ver nota 9 do manual."),
    ("Primeira instrução", 157, 158,
     "Numérico, 2 posições; conteúdo no manual: Código de instrução; ver nota 25 do manual."),
    ("Segunda instrução", 159, 160,
     "Numérico, 2 posições; conteúdo no manual: Código de instrução; ver nota 25 do manual."),
    ("Valor de Mora dia", 161, 173,
     "Numérico, 13 posições; 2 casas decimais, sem separador; conteúdo no manual: Dec. sem separador."),
    ("Data Limite para concessão do desconto", 174, 179,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA; ver nota 11 do manual."),
    ("Valor do desconto a ser concedido", 180, 192,
     "Numérico, 13 posições; 2 casas decimais, sem separador; conteúdo no manual: Dec. sem separador; ver nota 11 do manual."),
    ("Percentual do IOF a ser recolhido", 193, 205,
     "Numérico, 13 posições; 5 casas decimais, sem separador."),
    ("Valor do abatimento ou Valor do segundo desconto", 206, 218,
     "Numérico, 13 posições; 2 casas decimais, sem separador; ver nota 12 do manual."),
    ("Tipo de inscrição do Pagador", 219, 220,
     "Numérico, 2 posições; conteúdo no manual: 01 = CPF, 02 = CNPJ; ver nota 26 do manual."),
    ("Inscrição do Pagador", 221, 234,
     "Alfanumérico, 14 posições; ver nota 38 do manual."),
    ("Nome do Pagador", 235, 274,
     "Alfanumérico, 40 posições."),
    ("Endereço do Pagador", 275, 314,
     "Alfanumérico, 40 posições; ver nota 27 do manual."),
    ("Bairro do Pagador", 315, 326,
     "Alfanumérico, 12 posições; ver nota 27 do manual."),
    ("Cep do Pagador", 327, 331,
     "Numérico, 5 posições; ver nota 27 do manual."),
    ("Sufixo do Cep do Pagador", 332, 334,
     "Numérico, 3 posições; ver nota 27 do manual."),
    ("Cidade do Pagador", 335, 349,
     "Alfanumérico, 15 posições; ver nota 27 do manual."),
    ("Unidade de Federação do Pagador", 350, 351,
     "Alfanumérico, 2 posições; ver nota 27 do manual."),
    ("Uso Reservado (Filler)", 352, 381,
     "Reservado para uso do Banco (30 posições); conteúdo no manual: Brancos."),
    ("Uso Reservado (Filler)", 382, 382,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Identificador do complemento", 383, 383,
     "Alfanumérico, 1 posição; ver nota 2 do manual."),
    ("Complemento", 384, 385,
     "Numérico, 2 posições; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 386, 391,
     "Reservado para uso do Banco (6 posições); conteúdo no manual: Brancos."),
    ("Número de dias corridos para Protesto", 392, 393,
     "Numérico, 2 posições; ver nota 28 do manual."),
    ("Uso Reservado (Filler)", 394, 394,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Número sequencial do registro no arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# Qrcode Remessa
QRCODE_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Numérico, 1 posição; ver nota 8 do manual."),
    ("Identificação do tipo de pagamento", 2, 3,
     "Numérico, 2 posições; ver nota 16 do manual."),
    ("Quantidade de pagamento possíveis", 4, 5,
     "Numérico, 2 posições; ver nota 17 do manual."),
    ("Tipo de valor informado", 6, 6,
     "Numérico, 1 posição; ver nota 18 do manual."),
    ("Valor Máximo", 7, 19,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("% (Percentual) Máximo", 20, 24,
     "Numérico, 5 posições; 2 casas decimais, sem separador."),
    ("Valor Mínimo", 25, 37,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("% (Percentual) Mínimo", 38, 42,
     "Numérico, 5 posições; 2 casas decimais, sem separador."),
    ("Tipo de Chave DICT", 43, 43,
     "Alfanumérico, 1 posição; ver nota 34 do manual."),
    ("Código Chave DICT", 44, 120,
     "Alfanumérico, 77 posições; ver nota 35 do manual."),
    ("Código de identificação do Qr Code (TXID)", 121, 155,
     "Alfanumérico, 35 posições; ver nota 37 do manual."),
    ("Uso Reservado (Filler)", 156, 394,
     "Reservado para uso do Banco (239 posições); conteúdo no manual: Brancos."),
    ("Número sequencial do registro do arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# Mensagem Remessa
MENSAGEM_REMESSA_FIELDS = [
    ("Código do registro", 1, 1,
     "Numérico, 1 posição; conteúdo no manual: 2 = Recibo do Pagador; 4, 5, 6 e 7 = Ficha de Compensação."),
    ("Uso Reservado (Filler)", 2, 17,
     "Reservado para uso do Banco (16 posições)."),
    ("Código da Agência do Beneficiário", 18, 21,
     "Numérico, 4 posições; ver nota 2 do manual."),
    ("Conta Movimento Beneficiário", 22, 29,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Conta Cobrança Beneficiário", 30, 37,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 38, 47,
     "Reservado para uso do Banco (10 posições)."),
    ("Sub-sequência do registro (1ª mensagem)", 48, 49,
     "Numérico, 2 posições; ver nota 01 do manual."),
    ("Mensagem variável por boleto (1ª linha)", 50, 99,
     "Alfanumérico, 50 posições."),
    ("Sub-sequência do registro (2ª mensagem)", 100, 101,
     "Numérico, 2 posições; ver nota 02 do manual."),
    ("Mensagem variável por boleto (2ª linha)", 102, 151,
     "Alfanumérico, 50 posições."),
    ("Sub-sequência do registro (3ª mensagem)", 152, 153,
     "Numérico, 2 posições; ver nota 02 do manual."),
    ("Mensagem variável por boleto (3ª linha)", 154, 203,
     "Alfanumérico, 50 posições."),
    ("Uso Reservado (Filler)", 204, 382,
     "Reservado para uso do Banco (179 posições)."),
    ("Identificador do complemento", 383, 383,
     "Alfanumérico, 1 posição."),
    ("Complemento", 384, 385,
     "Numérico, 2 posições; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 386, 394,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Número sequencial do registro no arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# Trailer Remessa
TRAILER_REMESSA_FIELDS = [
    ("Código do Registro", 1, 1,
     "Numérico, 1 posição; ver nota 9 do manual."),
    ("Quantidade de registro no arquivo", 2, 7,
     "Numérico, 6 posições."),
    ("Valor Total dos boletos", 8, 20,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Uso Reservado (Filler)", 21, 394,
     "Reservado para uso do Banco (374 posições); conteúdo no manual: Zeros."),
    ("Número sequencial de registro no arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# --- Retorno ----------------------------------------------------------------------------------

# Header Retorno
HEADER_RETORNO_FIELDS = [
    ("Código do registro", 1, 1,
     "Numérico, 1 posição; ver nota 0 do manual."),
    ("Código da remessa", 2, 2,
     "Numérico, 1 posição; ver nota 2 do manual."),
    ("Literal de transmissão", 3, 9,
     "Alfanumérico, 7 posições; conteúdo no manual: RETORNO."),
    ("Código de serviço", 10, 11,
     "Numérico, 2 posições; ver nota 01 do manual."),
    ("Literal do serviço", 12, 26,
     "Alfanumérico, 15 posições; conteúdo no manual: COBRANCA."),
    ("Código da agência do beneficiário", 27, 30,
     "Numérico, 4 posições; ver nota 2 do manual."),
    ("Conta Movimento do beneficiário", 31, 38,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Conta Cobrança do beneficiário", 39, 46,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Nome do beneficiário", 47, 76,
     "Alfanumérico, 30 posições."),
    ("Código do banco", 77, 79,
     "Numérico, 3 posições; conteúdo no manual: 353/033."),
    ("Nome do banco", 80, 94,
     "Alfanumérico, 15 posições; conteúdo no manual: SANTANDER."),
    ("Data da geração do arquivo", 95, 100,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA."),
    ("Uso Reservado (Filler)", 101, 108,
     "Reservado para uso do Banco (8 posições); conteúdo no manual: Zeros."),
    ("Código do beneficiário", 109, 117,
     "Numérico, 9 posições."),
    ("Uso Reservado (Filler)", 118, 385,
     "Reservado para uso do Banco (268 posições); conteúdo no manual: Brancos."),
    ("Sigla da empresa no sistema", 386, 389,
     "Alfanumérico, 4 posições."),
    ("Uso Reservado (Filler)", 390, 391,
     "Reservado para uso do Banco (2 posições); conteúdo no manual: Brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Numérico, 3 posições; ver nota 32 do manual."),
    ("Número Sequencial do registro no arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# Detail Retorno
DETAIL_RETORNO_FIELDS = [
    ("Código do Registro", 1, 1,
     "Numérico, 1 posição; ver nota 1 do manual."),
    ("Tipo de inscrição do beneficiário", 2, 3,
     "Numérico, 2 posições; conteúdo no manual: 01 = CPF, 02 = CNPJ."),
    ("Inscrição do beneficiário", 4, 17,
     "Alfanumérico, 14 posições; ver nota 38 do manual."),
    ("Código de agência do beneficiário", 18, 21,
     "Numérico, 4 posições; ver nota 2 do manual."),
    ("Conta movimento do beneficiário", 22, 29,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Conta cobrança do beneficiário", 30, 37,
     "Numérico, 8 posições; ver nota 2 do manual."),
    ("Identificação do boleto na empresa cliente", 38, 62,
     "Alfanumérico, 25 posições; conteúdo no manual: Número atribuído pelo cliente."),
    ("Nosso Número (Identificação do boleto no banco)", 63, 70,
     "Numérico, 8 posições; conteúdo no manual: Nosso Número."),
    ("Uso Reservado (Filler)", 71, 107,
     "Reservado para uso do Banco (37 posições); conteúdo no manual: Brancos."),
    ("Tipo de Cobrança (Código da Carteira)", 108, 108,
     "Numérico, 1 posição; conteúdo no manual: Código da carteira; ver nota 20 do manual."),
    ("Código de Movimento de Retorno", 109, 110,
     "Código de movimento de retorno (evento ocorrido com o boleto): 01 Boleto não existe; 02 Entrada boleto Confirmada; 03 Entrada e instrução de boleto Rejeitada; 04 Transferência para carteira Simples; 05 Transferência para Carteira Penhor/Desconto/Cessão; 06 Liquidação do Boleto Efetivada; 07 Liquidação por Conta; 08 Liquidação por Saldo; 09 Baixa Automática; 10 Boleto Baixado Conforme Instrução; 11 Boletos em carteira (em ser); 12 Abatimento Concedido; ... Tabela completa em OCORRENCIA_CODES (nota 29 do manual)."),
    ("Data da ocorrência", 111, 116,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA."),
    ("Número do Documento (Seu Número)", 117, 126,
     "Alfanumérico, 10 posições; conteúdo no manual: Seu Número."),
    ("Nosso Número (Identificação do boleto no banco)", 127, 134,
     "Numérico, 8 posições; conteúdo no manual: Nosso Número."),
    ("Código Original da remessa", 135, 136,
     "Numérico, 2 posições; ver nota 30 do manual."),
    ("Código de Erro/Ocorrência (1ª ocorrência)", 137, 139,
     "Alfanumérico, 3 posições; conteúdo no manual: 1º ocorrência; ver nota 31 do manual."),
    ("Código de Erro/Ocorrência (2ª ocorrência)", 140, 142,
     "Alfanumérico, 3 posições; conteúdo no manual: 2º ocorrência; ver nota 31 do manual."),
    ("Código de Erro/Ocorrência (3ª ocorrência)", 143, 145,
     "Alfanumérico, 3 posições; conteúdo no manual: 3º ocorrência; ver nota 31 do manual."),
    ("Uso Reservado (Filler)", 146, 146,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Data de vencimento do boleto", 147, 152,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA."),
    ("Valor nominal do boleto", 153, 165,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Número do banco cobrador", 166, 168,
     "Numérico, 3 posições."),
    ("Código da agência recebedora do boleto", 169, 173,
     "Numérico, 5 posições."),
    ("Espécie do boleto", 174, 175,
     "Numérico, 2 posições; ver nota 24 do manual."),
    ("Valor da tarifa cobrada", 176, 188,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor de outras despesas", 189, 201,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor de juros de atraso", 202, 214,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor de IOF recolhido", 215, 227,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor do abatimento concedido", 228, 240,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor do desconto concedido", 241, 253,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor Pago (Valor total recebido)", 254, 266,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor do juros de mora", 267, 279,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Valor de outros créditos", 280, 292,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Uso Reservado (Filler)", 293, 293,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Identificação boleto aceite / não aceite", 294, 294,
     "Alfanumérico, 1 posição; conteúdo no manual: N= Não aceite."),
    ("Uso Reservado (Filler)", 295, 295,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Data da efetivação crédito", 296, 301,
     "Numérico, 6 posições; conteúdo no manual: DDMMAA."),
    ("Nome do Pagador", 302, 337,
     "Alfanumérico, 36 posições."),
    ("Identificador do complemento", 338, 338,
     "Alfanumérico, 1 posição; ver nota 2 do manual."),
    ("Código da moeda", 339, 340,
     "Numérico, 2 posições; ver nota 00 do manual."),
    ("Valor do boleto em outra unidade", 341, 353,
     "Numérico, 13 posições; 5 casas decimais, sem separador; conteúdo no manual: Não se aplica."),
    ("Valor do IOF em outra unidade", 354, 366,
     "Numérico, 13 posições; 5 casas decimais, sem separador; conteúdo no manual: Não se aplica."),
    ("Valor do débito ou crédito", 367, 379,
     "Numérico, 13 posições; 2 casas decimais, sem separador."),
    ("Identificação do lançamento", 380, 380,
     "Alfanumérico, 1 posição; conteúdo no manual: D = Débito, C = Crédito."),
    ("Uso Reservado (Filler)", 381, 383,
     "Reservado para uso do Banco (3 posições); conteúdo no manual: Brancos."),
    ("Complemento", 384, 385,
     "Numérico, 2 posições; ver nota 2 do manual."),
    ("Sigla da empresa no sistema", 386, 389,
     "Alfanumérico, 4 posições."),
    ("Uso Reservado (Filler)", 390, 391,
     "Reservado para uso do Banco (2 posições); conteúdo no manual: Brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Numérico, 3 posições; ver nota 32 do manual."),
    ("Número Sequencial do registro no arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# Qrcode Retorno
QRCODE_RETORNO_FIELDS = [
    ("Código do Registro", 1, 1,
     "Numérico, 1 posição; ver nota 2 do manual."),
    ("Tipo de Chave DICT / Brancos", 2, 2,
     "Alfanumérico, 1 posição; ver nota 34 do manual."),
    ("Código Chave DICT/URL Gerada", 3, 79,
     "Alfanumérico, 77 posições; ver nota 35/36 do manual."),
    ("Código de identificação do Qr Code (TXID)", 80, 114,
     "Alfanumérico, 35 posições; ver nota 37 do manual."),
    ("Brancos", 115, 391,
     "Alfanumérico, 277 posições; conteúdo no manual: Brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Numérico, 3 posições; ver nota 32 do manual."),
    ("Número Sequencial do Registro no Arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# Trailer Retorno
TRAILER_RETORNO_FIELDS = [
    ("Código de registro", 1, 1,
     "Numérico, 1 posição; ver nota 9 do manual."),
    ("Código da remessa", 2, 2,
     "Numérico, 1 posição; ver nota 2 do manual."),
    ("Código do Serviço", 3, 4,
     "Numérico, 2 posições; ver nota 01 do manual."),
    ("Código do banco", 5, 7,
     "Numérico, 3 posições; conteúdo no manual: 353 / 033."),
    ("Uso Reservado (Filler)", 8, 17,
     "Reservado para uso do Banco (10 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros na cobrança Simples", 18, 25,
     "Numérico, 8 posições."),
    ("Valor total dos boletos na cobrança Simples", 26, 39,
     "Numérico, 14 posições; 2 casas decimais, sem separador."),
    ("Número do aviso de cobrança Simples", 40, 47,
     "Numérico, 8 posições."),
    ("Uso Reservado (Filler)", 48, 97,
     "Reservado para uso do Banco (50 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros na cobrança caucionada", 98, 105,
     "Numérico, 8 posições."),
    ("Valor total dos boletos na cobrança caucionada", 106, 119,
     "Numérico, 14 posições; 2 casas decimais, sem separador."),
    ("Número do aviso da cobrança caucionada", 120, 127,
     "Numérico, 8 posições."),
    ("Uso Reservado (Filler)", 128, 137,
     "Reservado para uso do Banco (10 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros na cobrança descontada", 138, 145,
     "Numérico, 8 posições."),
    ("Valor total dos boletos na cobrança descontada", 146, 159,
     "Numérico, 14 posições; 2 casas decimais, sem separador."),
    ("Número do aviso da cobrança descontada", 160, 167,
     "Numérico, 8 posições."),
    ("Uso Reservado (Filler)", 168, 391,
     "Reservado para uso do Banco (224 posições); conteúdo no manual: Brancos."),
    ("Número Sequência do arquivo", 392, 394,
     "Numérico, 3 posições; ver nota 32 do manual."),
    ("Número Sequencial do registro do arquivo", 395, 400,
     "Numérico, 6 posições."),
]

# --- Tabelas de código ------------------------------------------------------------------------

COMANDO_REMESSA_CODES = {  # nota 21: código de movimento da remessa (posições 109-110 do Movimento)
    "01": "Entrada do boleto",
    "02": "Baixa do boleto",
    "04": "Concessão de abatimento",
    "05": "Cancelamento do abatimento",
    "06": "Alteração do vencimento",
    "07": "Alteração do número controle beneficiário",
    "08": "Alteração do Seu Número",
    "09": "Protestar",
    "15": "Transferência da carteira Simples para Cessão",
    "16": "Baixa de Cessão por Descaracterização",
    "17": "Baixa de Cessão por Pagamento",
    "18": "Sustar o protesto (Após início do ciclo de protesto)",
    "47": "Alteração do valor nominal do boleto",
    "48": "Alteração do valor mínimo/percentual",
    "49": "Alteração do valor máximo/percentual",
}

OCORRENCIA_CODES = {  # nota 29: código de movimento do retorno (posições 109-110 do Movimento)
    "01": "Boleto não existe",
    "02": "Entrada boleto Confirmada",
    "03": "Entrada e instrução de boleto Rejeitada",
    "04": "Transferência para carteira Simples",
    "05": "Transferência para Carteira Penhor/Desconto/Cessão",
    "06": "Liquidação do Boleto Efetivada",
    "07": "Liquidação por Conta",
    "08": "Liquidação por Saldo",
    "09": "Baixa Automática",
    "10": "Boleto Baixado Conforme Instrução",
    "11": "Boletos em carteira (em ser)",
    "12": "Abatimento Concedido",
    "13": "Abatimento Cancelado",
    "14": "Alteração de Vencimento",
    "15": "Confirmação de Protesto",
    "16": "Boleto Baixado/Liquidado",
    "17": "Liquidado em Cartório",
    "21": "Boleto Enviado a Cartório",
    "22": "Boleto Retirado do Cartório",
    "24": "Custas de Cartório",
    "25": "Boleto Protestado",
    "26": "Sustar Protesto",
    "27": "Cancelar Boleto Protestado",
    "35": "Boleto DDA Reconhecido pelo Pagador",
    "36": "Boleto DDA Não Reconhecido pelo Pagador",
    "37": "Boleto DDA Recusado pela PCR",
    "38": "Não Protestar (antes de iniciar o ciclo de protesto)",
    "39": "Espécie de Boleto não permite a instrução",
    "61": "Confirmação de Alteração do Valor Nominal do Boleto",
    "62": "Confirmação de Alteração do Valor ou Percentual mínimo",
    "63": "Confirmação de Alteração do Valor ou Percentual máximo",
    "93": "Pagamento do Boleto Recebido",
    "94": "Cancelamento do Pagamento Recebido",
}

ESPECIE_BOLETO_CODES = {  # nota 24: espécie do boleto (posições 148-149)
    "01": "DM Duplicata Mercantil",
    "02": "NP Nota Promissória",
    "03": "AP Apólice de Seguro",
    "05": "RC Recibo",
    "06": "DS Duplicata de Serviço",
    "07": "LC Letra de Cambio",
    "08": "BDP Boleto de Proposta",
    "19": "BCC Boleto de Cartão de Crédito",
    "33": "BDA Boleto de Depósito e Aporte (Nota 33)",
}

INSTRUCAO_CODES = {  # nota 25: primeira e segunda instrução (posições 157-160)
    "00": "Não há instruções",
    "02": "Baixar após quinze dias do vencimento",
    "03": "Baixar após 30 dias do vencimento",
    "04": "Não Baixar",
    "06": "Protestar (Vide posição 392/393)",
    "07": "Não Protestar",
    "08": "Não cobrar juros de mora",
}

ERRO_OCORRENCIA_CODES = {  # nota 31: códigos de erro/ocorrência do retorno (posições 137-145)
    "001": "Nosso Número não numérico",
    "002": "Valor do abatimento não numérico",
    "003": "Data do vencimento não numérica",
    "004": "Cobrança não numérica",
    "005": "Código da carteira não numérica",
    "006": "Código da carteira inválida",
    "007": "Espécie do documento invalida",
    "008": "Unidade de valor não numérica",
    "009": "Baixa não permitida - boleto penhor com garantia / Unidade de valor inválida",
    "010": "Código primeira instrução não numérica",
    "011": "Código segunda instrução não numérica",
    "012": "Valor do boleto em outra unidade",
    "013": "Valor do boleto não numérico",
    "014": "Valor de mora não numérico",
    "015": "Data emissão não numérica",
    "016": "Data de vencimento inválida",
    "017": "Código da agência cobradora não numérica",
    "018": "Valor do IOF não numérico",
    "019": "Número do CEP não numérico",
    "020": "Tipo de inscrição não numérica",
    "021": "Número do CNPJ ou CPF não numérico",
    "022": "Código de ocorrência inválido",
    "023": "Boleto liquidado",
    "024": "Total parcela não numérico",
    "025": "Valor desconto não numérico",
    "026": "Código banco cobrador inválido",
    "027": "Número parcelas carnê não numérico",
    "028": "Número parcelas carnê zerado",
    "029": "Valor de mora inválido",
    "030": "Data vencimento menor de quinze dias da data processamento",
    "031": "Instrução recusada pelo sistema de garantias",
    "038": "Movimento excluído por solicitação",
    "039": "Perfil não aceita boleto em banco correspondente",
    "040": "Cobrança rápida não aceita banco correspondente",
    "041": "Agência cobradora não encontrada",
    "042": "Conta cobrança inválida",
    "043": "Não baixar, complemento informado inválido",
    "044": "Não protestar, complemento informado inválido",
    "045": "Quantidade de dias para baixa não preenchido",
    "046": "Quantidade de dias para protesto não preenchido",
    "047": "Total parcelas informada não bate com o total de parcelas geradas",
    "048": "Carnê com parcelas com erro",
    "049": "Seu número não confere com o carnê",
    "050": "Número do boleto igual a zero",
    "051": "Boleto não encontrado",
    "052": "Ocorrência não acatada, boleto liquidado",
    "053": "Ocorrência não acatada, boleto baixado",
    "054": "Boleto com ordem de protesto já emitida",
    "055": "Ocorrência não acatada para boleto já protestado",
    "056": "Ocorrência não acatada, boleto não vencido",
    "057": "CEP do pagador incorreto",
    "058": "CNPJ/CPF incorreto",
    "059": "Instrução não permitida para o tipo de carteira / Instrução aceita apenas para cobrança simples",
    "060": "Espécie do documento não protestavel",
    "061": "Beneficiário sem carta de protesto",
    "062": "Pagador não protestavel",
    "063": "CEP não encontrado na tabela de praças",
    "064": "Tipo de cobrança não permite protesto",
    "065": "Pedido de sustação já solicitado",
    "066": "Sustação de protesto fora do prazo",
    "067": "Cliente não transmite registro de ocorrência",
    "068": "Tipo de vencimento inválido",
    "069": "Produto diferente da cobrança simples",
    "070": "Data prorrogação menor que a data do vencimento",
    "071": "Data antecipação maior que a data do vencimento",
    "072": "Data do documento superior a data da instrução",
    "073": "Abatimento maior ou igual ao valor do boleto",
    "074": "Primeiro desconto maior ou igual o valor do boleto",
    "075": "Segundo desconto maior ou igual valor do boleto",
    "076": "Terceiro desconto maior ou igual valor do boleto",
    "077": "Desconto por antecipação maior ou igual valor do boleto",
    "078": "Não existe abatimento para cancelar",
    "079": "Não existe primeiro desconto para cancelar",
    "080": "Não existe segundo desconto para cancelar",
    "081": "Não existe terceiro desconto para cancelar",
    "082": "Não existe desconto por antecipação para cancelar",
    "083": "Não existe multa por atraso para cancelar",
    "084": "Já existe o segundo desconto",
    "085": "Já existe o terceiro desconto",
    "086": "Data segundo desconto inválida",
    "087": "Data do terceiro desconto inválida",
    "088": "Data da instrução inválida",
    "089": "Data multa menor ou igual do vencimento",
    "090": "Existe desconto por antecipação",
    "091": "Tipo/número de inscrição do pagador inválido",
    "092": "Nosso número já cadastrado",
    "093": "Valor do boleto não informado",
    "094": "Valor boleto em outra moeda não informada",
    "095": "Perfil não aceita valor do boleto zerado",
    "096": "Espécie do documento não permite protesto",
    "097": "Espécie documento não permite IOF zerado",
    "098": "Data emissão inválida",
    "099": "Registro duplicado no movimento diário",
    "100": "Data emissão maior que a data de vencimento",
    "101": "Nome do Pagador não informado",
    "102": "Endereço do pagador não informado",
    "103": "Cidade do Pagador não informado",
    "104": "Unidade da federação não informada",
    "105": "Tipo de inscrição não existe",
    "106": "CNPJ/CPF não informado",
    "107": "Unidade da federação",
    "108": "Dígito CNPJ/CPF incorreto / Digito CNPJ/CPF incorreto",
    "109": "Valor de mora tem quer ser zero (boleto=zero)",
    "110": "Data do primeiro desconto inválida",
    "111": "Data desconto não numérica",
    "112": "Valor desconto não informado",
    "113": "Valor desconto inválido",
    "114": "Valor abatimento não informado",
    "115": "Valor abatimento maior que o valor do boleto",
    "116": "Data multa não numérico",
    "117": "Valor do abatimento é maior que o valor do boleto",
    "118": "Data multa não informado",
    "119": "Data multa maior que a data de vencimento",
    "120": "Percentual multa não numérico",
    "121": "Percentual multa não informado",
    "122": "Valor IOF maior que o valor do boleto",
    "123": "CEP do pagador não numérico",
    "124": "CEP do pagador não encontrado",
    "125": "Complemento da instrução não numérico",
    "128": "Código de protesto inválido",
    "129": "Espécie do documento não numérica",
    "130": "Forma de cadastramento não numérica",
    "131": "Forma de cadastramento inválida",
    "132": "Forma de cadastramento 2 invalida para carteira tipo 3",
    "133": "Forma de cadastramento 2 invalida para carteira tipo 4",
    "134": "Código do movimento remessa não numérico",
    "136": "Código banco na compensação não numérico",
    "137": "Código do banco na compensação inválido",
    "138": "Número do lote remessa detalhe não numérico",
    "139": "Tipo de registro inválido",
    "140": "Código segmento do registro detalhe inválido",
    "141": "Número sequencial do registro detalhe inválido",
    "142": "Número da agência cedente/digito não numérico",
    "143": "Número da conta cedente/dígito não numérico",
    "144": "Tipo de documento não numérico",
    "145": "Tipo de documento inválido",
    "146": "Código de protesto não numérico",
    "147": "Quantidade de dias para protesto inválido",
    "148": "Quantidade de dias para protesto não numérico",
    "149": "Código de mora inválido",
    "150": "Código de mora não numérico",
    "151": "Valor mora igual a zeros para o código de mora 1",
    "152": "Valor taxa mora igual a zeros para o código de cod mora 2",
    "153": "Valor mora diferente de zeros para código de mora 3",
    "154": "Valor mora não numérico para código de mora 2",
    "155": "Valor de mora inválido para código de mora 4",
    "156": "Quantidade de dias para baixa/devolução não numérico",
    "157": "Quantidade de dias baixa/devolução inválido para o código 1",
    "158": "Quantidade de dias baixa/devolução inválido para o código 2",
    "159": "Quantidade de dias baixa/devolução inválido para o código 3",
    "160": "Bairro do Pagador não informado",
    "161": "Tipo de inscrição CNPJ/CPF beneficiário final não numérico",
    "162": "Indicador de carnê não numérico",
    "163": "Número total de parcelas carnê inválido",
    "164": "Número do plano não numérico",
    "165": "Indicador de parcelas carnê inválido",
    "166": "Número sequencial de parcelas inválidas para indicador maior que zeros",
    "167": "Número sequencial de parcelas invalidas para indicador diferente de zeros",
    "168": "Número total parcelas inválidas para indicador maior que zeros",
    "169": "Número total de parcelas invalidas para indicador diferente de zeros",
    "170": "Forma de cadastramento 2 invalido para carteira tipo 5",
    "199": "Tipo inscrição CNPJ/CPF beneficiário final inválido",
    "200": "Número inscrição CNPJ beneficiário final inválido",
    "201": "Alteração do controle participante inválido",
    "202": "Alteração do Seu Número inválido",
    "371": "Boleto rejeitado - Operação de desconto",
    "372": "Boleto rejeitado - Horário limite operação desconto",
    "373": "Quantidade pagamentos possíveis inválidos",
    "374": "Valor nominal maior que o valor máximo do boleto",
    "375": "Valor nominal menor que o valor máximo do boleto",
    "378": "Tipo de valor inválido",
    "379": "Valor máximo inválido",
    "380": "Percentual máximo invalido / Percentual máximo inválido",
    "381": "Valor mínimo inválido",
    "382": "Percentual mínimo inválido",
    "383": "Instrução exige o registro tipo 8",
    "384": "Valor nominal incompatível com o tipo de pagamento",
    "385": "Valor nominal incompatível com espécie / Valor nominal incompatível com a espécie",
    "388": "Tipo de pagamento não numérico",
    "389": "Tipo de pagamento inválido",
    "390": "Quantidade de pagamentos possíveis não numéricos",
    "391": "Instrução não permitida para o boleto com reserva",
    "414": "Transferência não permitida",
    "417": "Operação Rejeitada – Horário Limite Excedido",
    "418": "Não foi realizada a contratação do produto SX Integra para operar com Cessão",
    "419": "Operação de Cessão Não Confirmada",
    "420": "Operação de Cessão Rejeitada – Ver detalhes no relatório do SX Integra",
    "494": "CNPJ Raiz do pagador não pode ser igual ao do beneficiário original",
    "497": "CPF do pagador não pode ser igual ao do beneficiário original",
    "500": "Registro não permitido – Beneficiário Final com restrição",
    "501": "Chave PIX Inválida",
    "502": "Chave PIX Sem Cadastro na DICT",
    "503": "Chave PIX Não é Compatível com CNPJ/CPF",
    "504": "Identificador Txid em duplicidade",
    "505": "Identificador Txid inválido ou não encontrado",
    "506": "Alteração não permitida - QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "507": "Cancelamento não permitido – QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "508": "Registrado com QR Code Pix",
    "509": "Registrado sem QR Code Pix",
    "510": "Baixado por Pagamento via Pix",
    "511": "Liquidado por Pagamento via Pix",
    "513": "Código de Moeda Inválido",
    "514": "Obrigatório informar o Beneficiário Final para o boleto",
    "515": "Instrução recusada - limite de alt.de vencto atingido p/ boletos em garantia",
    "516": "Instrução recusada, convenio com garantia em conta Escrow",
    "517": "Instrução não aceita – Pix Automático",
}


def _validate_contiguous(fields, name, width=400):
    """Confere que a lista cobre 1..400 sem lacunas nem sobreposição e que cada campo tem título e descrição."""
    esperado = 1
    for campo in fields:
        assert len(campo) == 4, f"{name}: campo com {len(campo)} itens: {campo!r}"
        titulo, inicio, fim, descricao = campo
        assert titulo and descricao, f"{name}: campo sem título ou descrição em {inicio}"
        assert inicio == esperado, f"{name}: '{titulo}' começa em {inicio}, esperado {esperado}"
        assert fim >= inicio, f"{name}: '{titulo}' termina antes de começar ({inicio}-{fim})"
        esperado = fim + 1
    assert esperado - 1 == width, f"{name}: termina em {esperado - 1}, esperado {width}"



if __name__ == "__main__":
    listas = [(n, v) for n, v in sorted(globals().items()) if n.endswith("_FIELDS") and isinstance(v, list)]
    for nome, campos in listas:
        _validate_contiguous(campos, nome)
        print(f"{nome}: {len(campos)} campos, 1..400 OK")
