# -*- coding: utf-8 -*-
"""
CNAB 240 Santander (banco 033) - Cobrança - referência de campos.

Fonte: "Layout Cobrança H7815 - CNAB 240 posições - padrão Santander/Multibanco", versão 8.5, fevereiro/2026
(manual oficial do Banco Santander, https://www.santander.com.br/layout-de-arquivos). As notas citadas nas
descrições são as notas desse manual.

Estrutura (posição 8 = tipo de registro; posição 14 = segmento do Registro Detalhe):
  Remessa: Header de Arquivo (0), Header de Lote (1), Segmentos P e Q (obrigatórios), R, S (opcionais),
           Trailer de Lote (5), Trailer de Arquivo (9).
  Retorno: Header de Arquivo, Header de Lote, Segmentos T e U (obrigatórios),
           Trailer de Lote, Trailer de Arquivo.

O Segmento S tem dois formatos, escolhidos pela posição 18 ("Identificação da impressão"): 1 = formulário
especial (mensagem por linha) e 2 = mensagens 5 a 9. Aqui são as listas SEGMENTO_S_1_REMESSA_FIELDS e
SEGMENTO_S_2_REMESSA_FIELDS.

Convenções de nome (a interface depende delas): o resumo da grade procura por trechos como "Data de
Vencimento", "Valor Nominal", "Nosso Número", "Número do Documento", "Código de Movimento", "Nome do
Pagador" e "Valor Pago"; campos reservados levam "Uso Reservado (Filler)" e aparecem acinzentados. Por
isso alguns títulos trazem, entre parênteses, o nome que o manual usa.

Observações sobre o manual: o Header de Arquivo da remessa mostra o banco como "33" (nas demais linhas é
"033"); o Segmento P chama a agência e a conta do Beneficiário de "Destinatária" (aqui, "Destinatário").
"""

# --- Remessa ----------------------------------------------------------------------------------

# HEADER_ARQUIVO_REMESSA_FIELDS
HEADER_ARQUIVO_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; conteúdo no manual: 0000; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 0; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 16,
     "Reservado para uso do Banco (8 posições); conteúdo no manual: Brancos."),
    ("Tipo de inscrição da empresa", 17, 17,
     "Numérico, 1 posição; conteúdo no manual: 1 = CPF, 2 = CNPJ."),
    ("Inscrição da empresa", 18, 32,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Código de Transmissão", 33, 47,
     "Numérico, 15 posições; ver nota 3 do manual."),
    ("Uso Reservado (Filler)", 48, 72,
     "Reservado para uso do Banco (25 posições); conteúdo no manual: Brancos."),
    ("Nome da empresa", 73, 102,
     "Alfanumérico, 30 posições."),
    ("Nome do Banco", 103, 132,
     "Alfanumérico, 30 posições; conteúdo no manual: Banco Santander."),
    ("Uso Reservado (Filler)", 133, 142,
     "Reservado para uso do Banco (10 posições); conteúdo no manual: Brancos."),
    ("Código remessa", 143, 143,
     "Numérico, 1 posição; conteúdo no manual: 1 = Remessa."),
    ("Data de geração do arquivo", 144, 151,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Uso Reservado (Filler)", 152, 157,
     "Reservado para uso do Banco (6 posições); conteúdo no manual: Brancos."),
    ("Nº seqüencial do arquivo", 158, 163,
     "Numérico, 6 posições; ver nota 4 do manual."),
    ("Nº da versão do layout do arquivo", 164, 166,
     "Numérico, 3 posições; conteúdo no manual: 040."),
    ("Uso Reservado (Filler)", 167, 240,
     "Reservado para uso do Banco (74 posições); conteúdo no manual: Brancos."),
]

# HEADER_LOTE_REMESSA_FIELDS
HEADER_LOTE_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 1; ver nota 2 do manual."),
    ("Tipo de operação", 9, 9,
     "Alfanumérico, 1 posição; conteúdo no manual: R (Remessa)."),
    ("Tipo de serviço", 10, 11,
     "Numérico, 2 posições; conteúdo no manual: 01 (Cobrança)."),
    ("Uso Reservado (Filler)", 12, 13,
     "Reservado para uso do Banco (2 posições); conteúdo no manual: Brancos."),
    ("Nº da versão do layout do lote", 14, 16,
     "Numérico, 3 posições; conteúdo no manual: 030."),
    ("Uso Reservado (Filler)", 17, 17,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Tipo de inscrição da empresa", 18, 18,
     "Numérico, 1 posição; conteúdo no manual: 1 = CPF, 2 = CNPJ."),
    ("Inscrição da empresa", 19, 33,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Uso Reservado (Filler)", 34, 53,
     "Reservado para uso do Banco (20 posições); conteúdo no manual: Brancos."),
    ("Código de Transmissão", 54, 68,
     "Numérico, 15 posições; ver nota 3 do manual."),
    ("Uso Reservado (Filler)", 69, 73,
     "Reservado para uso do Banco (5 posições); conteúdo no manual: Brancos."),
    ("Nome do Beneficiário", 74, 103,
     "Alfanumérico, 30 posições."),
    ("Mensagem 1", 104, 143,
     "Alfanumérico, 40 posições; ver nota 9 do manual."),
    ("Mensagem 2", 144, 183,
     "Alfanumérico, 40 posições; ver nota 9 do manual."),
    ("Número remessa/retorno", 184, 191,
     "Numérico, 8 posições; ver nota 10 do manual."),
    ("Data da gravação remessa/retorno", 192, 199,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Uso Reservado (Filler)", 200, 240,
     "Reservado para uso do Banco (41 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_P_REMESSA_FIELDS
SEGMENTO_P_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: P; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de movimento remessa", 16, 17,
     "Código de movimento da remessa (instrução comandada pelo Beneficiário): 01 Entrada de boleto; 02 Pedido de baixa; 04 Concessão de abatimento; 05 Cancelamento de abatimento; 06 Alteração de vencimento; 07 Alteração da identificação do boleto na empresa (Controle Participante); 08 Alteração seu número; 09 Pedido de Protesto; 18 Pedido de Sustação de Protesto; 10 Concessão de Desconto; 11 Cancelamento de desconto; 12 Transferência de Titularidade automática; 15 Transferência da carteira Simples para a carteira Cessão; 16 Baixa de Cessão por Descaracterização; 17 Baixa de Cessão por Pagamento; 31 Alteração de outros dados; 47 Alteração do Valor Nominal do boleto; 48 Alteração do Valor Mínimo ou Percentual Mínimo; 49 Alteração do Valor Máximo ou Percentual Máximo; 98 Não Protestar (Antes de iniciar o ciclo de protesto ). Tabela em MOVIMENTO_REMESSA_CODES (nota 14 do manual)."),
    ("Agência do Destinatário", 18, 21,
     "Numérico, 4 posições."),
    ("Dígito da Agência do Destinatário", 22, 22,
     "Numérico, 1 posição."),
    ("Número da conta corrente", 23, 31,
     "Numérico, 9 posições."),
    ("Dígito verificador da conta", 32, 32,
     "Numérico, 1 posição."),
    ("Conta cobrança Destinatário FIDC", 33, 41,
     "Numérico, 9 posições; ver nota 45 do manual."),
    ("Dígito da conta cobrança Destinatário FIDC", 42, 42,
     "Numérico, 1 posição."),
    ("Uso Reservado (Filler)", 43, 44,
     "Reservado para uso do Banco (2 posições); conteúdo no manual: Brancos."),
    ("Nosso Número (Identificação do boleto no Banco)", 45, 57,
     "Numérico, 13 posições; conteúdo no manual: Nosso Número; ver nota 15 do manual."),
    ("Tipo de cobrança", 58, 58,
     "Alfanumérico, 1 posição; ver nota 5 do manual."),
    ("Forma de Cadastramento", 59, 59,
     "Numérico, 1 posição; ver nota 6 do manual."),
    ("Tipo de documento", 60, 60,
     "Numérico, 1 posição; conteúdo no manual: 1- Tradicional, 2- Escritural."),
    ("Uso Reservado (Filler)", 61, 61,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Uso Reservado (Filler)", 62, 62,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Número do Documento (Seu Número)", 63, 77,
     "Alfanumérico, 15 posições; conteúdo no manual: Seu número; ver nota 16 do manual."),
    ("Data de vencimento do boleto", 78, 85,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA; ver nota 17 do manual."),
    ("Valor nominal do boleto", 86, 100,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: Decimais sem separador; ver nota 18 do manual."),
    ("Agência encarregada da cobrança FIDC", 101, 104,
     "Numérico, 4 posições; ver nota 44 do manual."),
    ("Dígito da Agência do Beneficiário FIDC", 105, 105,
     "Numérico, 1 posição; ver nota 44 do manual."),
    ("Uso Reservado (Filler)", 106, 106,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Espécie do boleto", 107, 108,
     "Numérico, 2 posições; ver nota 20 do manual."),
    ("Identif. de boleto Aceito/Não Aceito", 109, 109,
     "Alfanumérico, 1 posição; conteúdo no manual: N- Não Aceite."),
    ("Data da emissão do boleto", 110, 117,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Código de juros de mora", 118, 118,
     "Numérico, 1 posição; ver nota 21 do manual."),
    ("Data de juros de mora", 119, 126,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA; ver nota 22 do manual."),
    ("Valor da mora/dia ou Taxa mensal", 127, 141,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: Decimais, sem separador; ver nota 18 do manual."),
    ("Código do desconto 1", 142, 142,
     "Numérico, 1 posição; ver nota 23 do manual."),
    ("Data de desconto 1", 143, 150,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA; ver nota 23 do manual."),
    ("Valor ou Percentual do desconto concedido", 151, 165,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: Decimais sem separador."),
    ("Percentual do IOF a ser recolhido", 166, 180,
     "Numérico, 15 posições; 5 casas decimais, sem separador; conteúdo no manual: Decimais sem separador; ver nota 18 do manual."),
    ("Valor do abatimento", 181, 195,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: Decimais sem separador; ver nota 18 do manual."),
    ("Identificação do boleto na empresa", 196, 220,
     "Alfanumérico, 25 posições; conteúdo no manual: Uso Beneficiário (opcional); ver nota 24 do manual."),
    ("Código para protesto", 221, 221,
     "Numérico, 1 posição; ver nota 25 do manual."),
    ("Número de dias para protesto", 222, 223,
     "Numérico, 2 posições."),
    ("Código para Baixa/Devolução", 224, 224,
     "Numérico, 1 posição; ver nota 26 do manual."),
    ("Uso Reservado (Filler)", 225, 225,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Zero Fixo."),
    ("Número de dias para Baixa/Devolução", 226, 227,
     "Numérico, 2 posições."),
    ("Código da moeda", 228, 229,
     "Numérico, 2 posições; ver nota 27 do manual."),
    ("Uso Reservado (Filler)", 230, 240,
     "Reservado para uso do Banco (11 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_Q_REMESSA_FIELDS
SEGMENTO_Q_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: Q; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de movimento remessa", 16, 17,
     "Numérico, 2 posições; ver nota 14 do manual."),
    ("Tipo de inscrição do Pagador", 18, 18,
     "Numérico, 1 posição; conteúdo no manual: 1 = CPF, 2 = CNPJ; ver nota 29 do manual."),
    ("Inscrição do Pagador", 19, 33,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Nome do Pagador", 34, 73,
     "Alfanumérico, 40 posições."),
    ("Endereço do Pagador", 74, 113,
     "Alfanumérico, 40 posições; ver nota 28 do manual."),
    ("Bairro do Pagador", 114, 128,
     "Alfanumérico, 15 posições; ver nota 28 do manual."),
    ("Cep do Pagador", 129, 133,
     "Numérico, 5 posições; ver nota 28 do manual."),
    ("Sufixo do Cep do Pagador", 134, 136,
     "Numérico, 3 posições; ver nota 28 do manual."),
    ("Cidade do Pagador", 137, 151,
     "Alfanumérico, 15 posições; ver nota 28 do manual."),
    ("Unidade da Federação do Pagador", 152, 153,
     "Alfanumérico, 2 posições; ver nota 28 do manual."),
    ("Tipo de inscrição Beneficiário Final", 154, 154,
     "Numérico, 1 posição; conteúdo no manual: 1 = CPF, 2 = CNPJ; ver nota 29 do manual."),
    ("Inscrição Beneficiário Final", 155, 169,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 30 e 54 do manual."),
    ("Nome do Beneficiário Final", 170, 209,
     "Alfanumérico, 40 posições; ver nota 30 do manual."),
    ("Uso Reservado (Filler)", 210, 212,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 213, 215,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 216, 218,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 219, 221,
     "Reservado para uso do Banco (3 posições)."),
    ("Uso Reservado (Filler)", 222, 240,
     "Reservado para uso do Banco (19 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_R_REMESSA_FIELDS
SEGMENTO_R_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Código segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: R; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de movimento", 16, 17,
     "Numérico, 2 posições; ver nota 14 do manual."),
    ("Código do desconto 2", 18, 18,
     "Numérico, 1 posição; ver nota 23 do manual."),
    ("Data do desconto 2", 19, 26,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Valor/Percentual a ser concedido", 27, 41,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Código do desconto 3", 42, 42,
     "Numérico, 1 posição; ver nota 23 do manual."),
    ("Data do desconto 3", 43, 50,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Valor/Percentual a ser concedido", 51, 65,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Código da multa", 66, 66,
     "Numérico, 1 posição; conteúdo no manual: 1- Valor fixo, 2- Percentual."),
    ("Data da multa", 67, 74,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA; ver nota 32 do manual."),
    ("Valor/Percentual a ser aplicado", 75, 89,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador."),
    ("Uso Reservado (Filler)", 90, 99,
     "Reservado para uso do Banco (10 posições); conteúdo no manual: Brancos."),
    ("Mensagem 3", 100, 139,
     "Alfanumérico, 40 posições; ver nota 33 do manual."),
    ("Mensagem 4", 140, 179,
     "Alfanumérico, 40 posições; ver nota 33 do manual."),
    ("Uso Reservado (Filler)", 180, 240,
     "Reservado para uso do Banco (61 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_S_1_REMESSA_FIELDS (Segmento S, impressão 1)
SEGMENTO_S_1_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: S; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Branco."),
    ("Código de movimento", 16, 17,
     "Numérico, 2 posições; ver nota 14 do manual."),
    ("Identificação da impressão", 18, 18,
     "Numérico, 1 posição; conteúdo no manual: 1; ver nota 34 do manual."),
    ("Número da linha a ser impressa", 19, 20,
     "Numérico, 2 posições; conteúdo no manual: De 01 a 22; ver nota 35 do manual."),
    ("Mensagem para recibo do Pagador", 21, 21,
     "Numérico, 1 posição; conteúdo no manual: 2 ou 4; ver nota 36 do manual."),
    ("Mensagem a ser impressa", 22, 121,
     "Alfanumérico, 100 posições."),
    ("Uso Reservado (Filler)", 122, 240,
     "Reservado para uso do Banco (119 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_S_2_REMESSA_FIELDS (Segmento S, impressão 2)
SEGMENTO_S_2_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro de lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. Segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: S; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Branco."),
    ("Código de movimento", 16, 17,
     "Numérico, 2 posições; ver nota 14 do manual."),
    ("Identificação da impressão", 18, 18,
     "Numérico, 1 posição; conteúdo no manual: 2; ver nota 34 do manual."),
    ("Mensagem 5", 19, 58,
     "Alfanumérico, 40 posições."),
    ("Mensagem 6", 59, 98,
     "Alfanumérico, 40 posições."),
    ("Mensagem 7", 99, 138,
     "Alfanumérico, 40 posições."),
    ("Mensagem 8", 139, 178,
     "Alfanumérico, 40 posições; conteúdo no manual: Brancos."),
    ("Mensagem 9", 179, 218,
     "Alfanumérico, 40 posições; conteúdo no manual: Brancos."),
    ("Uso Reservado (Filler)", 219, 240,
     "Reservado para uso do Banco (22 posições); conteúdo no manual: Brancos."),
]

# TRAILER_LOTE_REMESSA_FIELDS
TRAILER_LOTE_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 353 / 008 / 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 5; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros do lote", 18, 23,
     "Numérico, 6 posições; ver nota 37 do manual."),
    ("Uso Reservado (Filler)", 24, 240,
     "Reservado para uso do Banco (217 posições); conteúdo no manual: Brancos."),
]

# TRAILER_ARQUIVO_REMESSA_FIELDS
TRAILER_ARQUIVO_REMESSA_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 9; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de lotes do arquivo", 18, 23,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=1."),
    ("Quantidade de registros do arquivo", 24, 29,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=0+1+2+3+5+9."),
    ("Uso Reservado (Filler)", 30, 240,
     "Reservado para uso do Banco (211 posições); conteúdo no manual: Brancos."),
]

# --- Retorno ----------------------------------------------------------------------------------

# HEADER_ARQUIVO_RETORNO_FIELDS
HEADER_ARQUIVO_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; conteúdo no manual: 0000; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 0; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 16,
     "Reservado para uso do Banco (8 posições); conteúdo no manual: Brancos."),
    ("Tipo de inscrição da empresa", 17, 17,
     "Numérico, 1 posição; conteúdo no manual: 1 = CPF, 2 = CNPJ."),
    ("Inscrição da empresa", 18, 32,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Agência do Beneficiário", 33, 36,
     "Numérico, 4 posições; ver nota 3 do manual."),
    ("Dígito da Agência do Beneficiário", 37, 37,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Número da conta corrente", 38, 46,
     "Numérico, 9 posições; ver nota 3 do manual."),
    ("Dígito verificador da conta", 47, 47,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Uso Reservado (Filler)", 48, 52,
     "Reservado para uso do Banco (5 posições); conteúdo no manual: Brancos."),
    ("Código do Beneficiário", 53, 61,
     "Numérico, 9 posições."),
    ("Uso Reservado (Filler)", 62, 72,
     "Reservado para uso do Banco (11 posições); conteúdo no manual: Brancos."),
    ("Nome da empresa", 73, 102,
     "Alfanumérico, 30 posições."),
    ("Nome do Banco", 103, 132,
     "Alfanumérico, 30 posições; conteúdo no manual: BANCO SANTANDER."),
    ("Uso Reservado (Filler)", 133, 142,
     "Reservado para uso do Banco (10 posições); conteúdo no manual: Brancos."),
    ("Código remessa / retorno", 143, 143,
     "Numérico, 1 posição; conteúdo no manual: 2 – Retorno."),
    ("Data de geração do arquivo", 144, 151,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Uso Reservado (Filler)", 152, 157,
     "Reservado para uso do Banco (6 posições); conteúdo no manual: Brancos."),
    ("Nº seqüencial do arquivo", 158, 163,
     "Numérico, 6 posições; ver nota 4 do manual."),
    ("Nº da versão do layout do arquivo", 164, 166,
     "Numérico, 3 posições; conteúdo no manual: 040."),
    ("Uso Reservado (Filler)", 167, 240,
     "Reservado para uso do Banco (74 posições); conteúdo no manual: Brancos."),
]

# HEADER_LOTE_RETORNO_FIELDS
HEADER_LOTE_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote retorno", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 1; ver nota 2 do manual."),
    ("Tipo de operação", 9, 9,
     "Alfanumérico, 1 posição; conteúdo no manual: T."),
    ("Tipo de serviço", 10, 11,
     "Numérico, 2 posições; ver nota 01 do manual."),
    ("Uso Reservado (Filler)", 12, 13,
     "Reservado para uso do Banco (2 posições); conteúdo no manual: Brancos."),
    ("Nº da versão do layout do lote", 14, 16,
     "Numérico, 3 posições; conteúdo no manual: 040."),
    ("Uso Reservado (Filler)", 17, 17,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Tipo de inscrição da empresa", 18, 18,
     "Numérico, 1 posição; conteúdo no manual: 1 = CPF, 2 = CNPJ."),
    ("Inscrição da empresa", 19, 33,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Código do Beneficiário", 34, 42,
     "Numérico, 9 posições."),
    ("Uso Reservado (Filler)", 43, 53,
     "Reservado para uso do Banco (11 posições)."),
    ("Agência do Beneficiário", 54, 57,
     "Numérico, 4 posições; ver nota 3 do manual."),
    ("Dígito da Agência do Beneficiário", 58, 58,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Número da conta do Beneficiário", 59, 67,
     "Numérico, 9 posições; ver nota 3 do manual."),
    ("Dígito verificador da conta", 68, 68,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Uso Reservado (Filler)", 69, 73,
     "Reservado para uso do Banco (5 posições)."),
    ("Nome da empresa", 74, 103,
     "Alfanumérico, 30 posições."),
    ("Uso Reservado (Filler)", 104, 183,
     "Reservado para uso do Banco (80 posições)."),
    ("Número do Retorno", 184, 191,
     "Numérico, 8 posições; ver nota 10 do manual."),
    ("Data da gravação remessa/retorno", 192, 199,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Uso Reservado (Filler)", 200, 240,
     "Reservado para uso do Banco (41 posições); conteúdo no manual: Brancos."),
]

# SEGMENTO_T_RETORNO_FIELDS
SEGMENTO_T_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote retorno", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº sequencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: T; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de Movimento (Ocorrência)", 16, 17,
     "Código de movimento de retorno (evento ocorrido com o boleto): 02 Entrada confirmada; 03 Entrada rejeitada; 04 transferência para carteira Simples; 05 transferência para carteira Desconto/Penhor/Vendor/FIDC/Cessão; 06 Liquidação do Boleto Efetivada; 08 Confirmação do Recebimento do Cancelamento do Desconto; 09 Baixa; 11 boletos em carteira (em ser); 12 confirmação recebimento instrução de abatimento; 13 confirmação recebimento instrução de cancelamento abatimento; 14 confirmação recebimento instrução alteração de vencimento; 17 liquidação após baixa ou liquidação boleto não registrado; ... Tabela completa em MOVIMENTO_RETORNO_CODES (nota 40 do manual)."),
    ("Agência do Beneficiário", 18, 21,
     "Numérico, 4 posições; ver nota 3 do manual."),
    ("Dígito da Agência do Beneficiário", 22, 22,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Número da conta corrente", 23, 31,
     "Numérico, 9 posições; ver nota 3 do manual."),
    ("Dígito verificador da conta", 32, 32,
     "Numérico, 1 posição; ver nota 3 do manual."),
    ("Uso Reservado (Filler)", 33, 40,
     "Reservado para uso do Banco (8 posições); conteúdo no manual: Brancos."),
    ("Nosso Número (Identificação do boleto no Banco)", 41, 53,
     "Numérico, 13 posições; conteúdo no manual: Nosso número; ver nota 15 do manual."),
    ("Código da carteira", 54, 54,
     "Alfanumérico, 1 posição; ver nota 5 do manual."),
    ("Número do Documento (Seu Número)", 55, 69,
     "Alfanumérico, 15 posições; conteúdo no manual: Seu número; ver nota 16 do manual."),
    ("Data de Vencimento do boleto", 70, 77,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Valor nominal do boleto", 78, 92,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Nº do Banco Cobrador / Recebedor", 93, 95,
     "Numérico, 3 posições."),
    ("Agência Cobradora / Recebedora", 96, 99,
     "Numérico, 4 posições; ver nota 53 do manual."),
    ("Dígito da Agência do Beneficiário", 100, 100,
     "Numérico, 1 posição."),
    ("Identif. do boleto na empresa", 101, 125,
     "Alfanumérico, 25 posições; conteúdo no manual: Uso Beneficiário (opcional); ver nota 24 do manual."),
    ("Código da moeda", 126, 127,
     "Numérico, 2 posições; ver nota 26 do manual."),
    ("Tipo de inscrição Pagador", 128, 128,
     "Numérico, 1 posição; conteúdo no manual: 1 =CPF, 2 = CNPJ; ver nota 29 do manual."),
    ("Inscrição Pagador", 129, 143,
     "Alfanumérico, 15 posições; conteúdo no manual: Zero(s) + Documento; ver nota 54 do manual."),
    ("Nome do Pagador", 144, 183,
     "Alfanumérico, 40 posições."),
    ("Conta Cobrança", 184, 193,
     "Alfanumérico, 10 posições."),
    ("Valor da Tarifa/Custas", 194, 208,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador."),
    ("Identificação para rejeições, tarifas, custas, liquidações, baixas e PIX.", 209, 218,
     "Alfanumérico, 10 posições; conteúdo no manual: ocorre 5 vezes; cada ocorrência ocupa 2 dígitos; ver nota 40-A e 40-C do manual."),
    ("Uso Reservado (Filler)", 219, 240,
     "Reservado para uso do Banco (22 posições)."),
]

# SEGMENTO_U_RETORNO_FIELDS
SEGMENTO_U_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 3; ver nota 2 do manual."),
    ("Nº seqüencial do registro no lote", 9, 13,
     "Numérico, 5 posições; ver nota 11 do manual."),
    ("Cód. segmento do registro detalhe", 14, 14,
     "Alfanumérico, 1 posição; conteúdo no manual: U; ver nota 13 do manual."),
    ("Uso Reservado (Filler)", 15, 15,
     "Reservado para uso do Banco (1 posição); conteúdo no manual: Brancos."),
    ("Código de Movimento (Ocorrência)", 16, 17,
     "Código de movimento de retorno, o mesmo do Segmento T do título. Tabela em MOVIMENTO_RETORNO_CODES (nota 40 do manual)."),
    ("Juros / Multa / Encargos", 18, 32,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor do desconto concedido", 33, 47,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor do Abatimento Concedido/Cancelado", 48, 62,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor do IOF recolhido", 63, 77,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor Pago pelo Pagador", 78, 92,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor liquido a ser creditado", 93, 107,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor de outras despesas", 108, 122,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Valor de outros créditos", 123, 137,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Data da ocorrência", 138, 145,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Data da efetivação do crédito", 146, 153,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Código da ocorrência do Pagador", 154, 157,
     "Numérico, 4 posições; ver nota 41 do manual."),
    ("Data da ocorrência do Pagador", 158, 165,
     "Numérico, 8 posições; conteúdo no manual: DDMMAAAA."),
    ("Valor da ocorrência do Pagador", 166, 180,
     "Numérico, 15 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Complemento da ocorrência do Pagador", 181, 210,
     "Alfanumérico, 30 posições; ver nota 41 do manual."),
    ("Código do Banco correspondente na compensação", 211, 213,
     "Numérico, 3 posições; ver nota 31 do manual."),
    ("Uso Reservado (Filler)", 214, 240,
     "Reservado para uso do Banco (27 posições); conteúdo no manual: Brancos."),
]

# TRAILER_LOTE_RETORNO_FIELDS
TRAILER_LOTE_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Lote de serviço", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 5; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de registros do lote", 18, 23,
     "Numérico, 6 posições; ver nota 37 do manual."),
    ("Quantidade de Boletos cobrança simples", 24, 29,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos cobrança simples", 30, 46,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Quantidade de Boletos em cobrança vinculada", 47, 52,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos em cobrança vinculada", 53, 69,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Quantidade de Boletos em cobrança caucionada", 70, 75,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos em cobrança caucionada", 76, 92,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Quantidade de Boletos em cobrança descontada", 93, 98,
     "Numérico, 6 posições; ver nota 38 do manual."),
    ("Valor total dos Boletos em cobrança descontada", 99, 115,
     "Numérico, 17 posições; 2 casas decimais, sem separador; conteúdo no manual: decimais sem separador; ver nota 18 do manual."),
    ("Número do aviso de lançamento", 116, 123,
     "Alfanumérico, 8 posições; ver nota 39 do manual."),
    ("Uso Reservado (Filler)", 124, 240,
     "Reservado para uso do Banco (117 posições); conteúdo no manual: Brancos."),
]

# TRAILER_ARQUIVO_RETORNO_FIELDS
TRAILER_ARQUIVO_RETORNO_FIELDS = [
    ("Código do Banco na compensação", 1, 3,
     "Numérico, 3 posições; conteúdo no manual: 033."),
    ("Número do lote remessa", 4, 7,
     "Numérico, 4 posições; ver nota 1 do manual."),
    ("Tipo de registro", 8, 8,
     "Numérico, 1 posição; conteúdo no manual: 9; ver nota 2 do manual."),
    ("Uso Reservado (Filler)", 9, 17,
     "Reservado para uso do Banco (9 posições); conteúdo no manual: Brancos."),
    ("Quantidade de lotes do arquivo", 18, 23,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=1."),
    ("Quantidade de registros do arquivo", 24, 29,
     "Numérico, 6 posições; conteúdo no manual: Registros tipo=0+1+3+5+9."),
    ("Uso Reservado (Filler)", 30, 240,
     "Reservado para uso do Banco (211 posições); conteúdo no manual: Brancos."),
]

# --- Mapas por segmento e tipo de registro --------------------------------------------------------

SEGMENTOS = {
    ("Remessa", "P"): SEGMENTO_P_REMESSA_FIELDS,
    ("Remessa", "Q"): SEGMENTO_Q_REMESSA_FIELDS,
    ("Remessa", "R"): SEGMENTO_R_REMESSA_FIELDS,
    ("Remessa", "S-1"): SEGMENTO_S_1_REMESSA_FIELDS,
    ("Remessa", "S-2"): SEGMENTO_S_2_REMESSA_FIELDS,
    ("Retorno", "T"): SEGMENTO_T_RETORNO_FIELDS,
    ("Retorno", "U"): SEGMENTO_U_RETORNO_FIELDS,
}

REGISTROS = {
    ("Remessa", "0"): HEADER_ARQUIVO_REMESSA_FIELDS,
    ("Retorno", "0"): HEADER_ARQUIVO_RETORNO_FIELDS,
    ("Remessa", "1"): HEADER_LOTE_REMESSA_FIELDS,
    ("Retorno", "1"): HEADER_LOTE_RETORNO_FIELDS,
    ("Remessa", "5"): TRAILER_LOTE_REMESSA_FIELDS,
    ("Retorno", "5"): TRAILER_LOTE_RETORNO_FIELDS,
    ("Remessa", "9"): TRAILER_ARQUIVO_REMESSA_FIELDS,
    ("Retorno", "9"): TRAILER_ARQUIVO_RETORNO_FIELDS,
}

# --- Tabelas de código ------------------------------------------------------------------------

MOVIMENTO_REMESSA_CODES = {  # nota 14: código de movimento da remessa (posições 16-17 dos Segmentos P, Q, R e S)
    "01": "Entrada de boleto",
    "02": "Pedido de baixa",
    "04": "Concessão de abatimento",
    "05": "Cancelamento de abatimento",
    "06": "Alteração de vencimento",
    "07": "Alteração da identificação do boleto na empresa (Controle Participante)",
    "08": "Alteração seu número",
    "09": "Pedido de Protesto",
    "18": "Pedido de Sustação de Protesto",
    "10": "Concessão de Desconto",
    "11": "Cancelamento de desconto",
    "12": "Transferência de Titularidade automática",
    "15": "Transferência da carteira Simples para a carteira Cessão",
    "16": "Baixa de Cessão por Descaracterização",
    "17": "Baixa de Cessão por Pagamento",
    "31": "Alteração de outros dados",
    "47": "Alteração do Valor Nominal do boleto",
    "48": "Alteração do Valor Mínimo ou Percentual Mínimo",
    "49": "Alteração do Valor Máximo ou Percentual Máximo",
    "98": "Não Protestar (Antes de iniciar o ciclo de protesto )",
}

MOVIMENTO_RETORNO_CODES = {  # nota 40: código de movimento do retorno (posições 16-17 dos Segmentos T e U)
    "02": "Entrada confirmada",
    "03": "Entrada rejeitada",
    "04": "transferência para carteira Simples",
    "05": "transferência para carteira Desconto/Penhor/Vendor/FIDC/Cessão",
    "06": "Liquidação do Boleto Efetivada",
    "08": "Confirmação do Recebimento do Cancelamento do Desconto",
    "09": "Baixa",
    "11": "boletos em carteira (em ser)",
    "12": "confirmação recebimento instrução de abatimento",
    "13": "confirmação recebimento instrução de cancelamento abatimento",
    "14": "confirmação recebimento instrução alteração de vencimento",
    "17": "liquidação após baixa ou liquidação boleto não registrado",
    "19": "confirmação recebimento instrução de protesto",
    "20": "confirmação recebimento instrução de sustação/Não Protestar",
    "23": "remessa a cartório (aponte em cartório)",
    "24": "retirada de cartorio e manutenção em carteira",
    "25": "protestado e baixado (baixa por ter sido protestado)",
    "26": "instrução rejeitada",
    "27": "confirmação do pedido de alteração de outros dados",
    "28": "débito de tarifas/custas",
    "29": "ocorrências do Pagador",
    "30": "alteração de dados rejeitada",
    "32": "Código de IOF inválido",
    "51": "Boleto DDA reconhecido pelo Pagador",
    "52": "Boleto DDA não reconhecido pelo Pagador",
    "53": "Boleto DDA recusado pela PCR",
    "61": "Confirmação de Alteração do Valor Nominal do Boleto",
    "91": "Confirmação de Alteração do Valor Mínimo ou Percentual Mínimo",
    "92": "Confirmação de Alteração do Valor Máximo ou Percentual Máximo",
    "93": "Pagamento do Boleto Recebido",
    "94": "Cancelamento do Pagamento Recebido",
    "A4": "Pagador DDA",
}

ESPECIE_BOLETO_CODES = {  # nota 20: espécie do boleto (posições 107-108 do Segmento P)
    "02": "DM - DUPLICATA MERCANTIL",
    "04": "DS - DUPLICATA DE SERVICO",
    "07": "LC - LETRA DE CÂMBIO (SOMENTE PARA BANCO 353)",
    "30": "LC - LETRA DE CÂMBIO (SOMENTE PARA BANCO 008)",
    "12": "NP - NOTA PROMISSORIA",
    "13": "NR - NOTA PROMISSORIA RURAL",
    "17": "RC - RECIBO",
    "20": "AP – APOLICE DE SEGURO",
    "31": "BCC – CARTÃO DE CRÉDITO",
    "32": "BDP – BOLETO DE PROPOSTA",
    "33": "BDA – BOLETO DE DEPOSITO E APORTE",
    "97": "CH – CHEQUE",
    "98": "ND - NOTA PROMISSORIA DIRETA",
}

REJEICAO_CODES = {  # nota 40-A: rejeições associadas aos movimentos 03, 26 e 30 (Segmento T, posições 209-218)
    "01": "código do banco invalido",
    "02": "código do registro detalhe inválido",
    "03": "código do segmento invalido",
    "04": "código do movimento não permitido para carteira",
    "05": "código de movimento invalido",
    "06": "tipo/numero de inscrição do Beneficiário inválidos",
    "07": "agencia/conta/DV invalido",
    "08": "nosso numero invalido",
    "09": "nosso numero duplicado",
    "10": "carteira invalida",
    "11": "forma de cadastramento do boleto invalida Se Desconto ou Cessão, boleto rejeitado - operação de Desconto ou Cessão fora do horário limite.",
    "12": "tipo de documento invalido",
    "13": "identificação da emissão do Boleto invalida",
    "14": "identificação da distribuição do Boleto invalida",
    "15": "características da cobrança incompatíveis",
    "16": "data de vencimento invalida",
    "17": "data de vencimento anterior a data de emissão",
    "18": "vencimento fora do prazo de operação",
    "19": "boleto a cargo de bancos correspondentes com vencimento inferior a xx dias",
    "20": "valor do boleto invalido",
    "21": "espécie do boleto invalida",
    "22": "espécie não permitida para a carteira",
    "23": "aceite invalido",
    "24": "Data de emissão inválida",
    "25": "Data de emissão posterior a data de entrada",
    "26": "Código de juros de mora inválido",
    "27": "Valor/Taxa de juros de mora inválido",
    "28": "Código de desconto inválido",
    "29": "Valor do desconto maior ou igual ao valor do boleto",
    "30": "Desconto a conceder não confere",
    "31": "Concessão de desconto - já existe desconto anterior",
    "32": "Valor do IOF",
    "33": "Valor do abatimento inválido",
    "34": "Valor do abatimento maior ou igual ao valor do boleto",
    "35": "Abatimento a conceder não confere",
    "36": "Concessão de abatimento - já existe abatimento anterior",
    "37": "Código para protesto inválido",
    "38": "Prazo para protesto inválido",
    "39": "Pedido de protesto não permitido para o boleto",
    "40": "Boleto com ordem de protesto emitida",
    "41": "Pedido de cancelamento/sustação para boletos sem instrução de protesto",
    "42": "Código para baixa/devolução inválido",
    "43": "Prazo para baixa/devolução inválido",
    "44": "Boleto já baixado",
    "45": "Nome do Pagador não informado",
    "46": "Tipo /Número de inscrição do Pagador inválidos",
    "47": "Endereço do Pagador não informado",
    "48": "CEP inválido",
    "49": "CEP sem praça de cobrança (não localizado)",
    "50": "CEP referente a um Banco Correspondente",
    "51": "CEP incompatível com a unidade de federação",
    "52": "Unidade de federação inválida",
    "53": "Tipo/Número de inscrição do sacador/avalista inválidos",
    "54": "Sacador/Avalista não informado",
    "55": "Nosso número no Banco Correspondente não informado",
    "56": "Código do Banco Correspondente não informado",
    "57": "Código da multa inválido",
    "58": "Data da multa inválida",
    "59": "Valor/Percentual da multa inválido",
    "60": "Movimento para boleto não cadastrado",
    "61": "Alteração de agência cobradora/dv inválida",
    "62": "Tipo de impressão inválido",
    "63": "Entrada para boleto já cadastrado",
    "64": "Número da linha inválido",
    "65": "A espécie de boleto não permite a instrução",
    "72": "Entrada de boleto Sem Registro",
    "90": "Identificador/Quantidade de Parcelas de carnê invalido",
    "91": "Boleto Descontado, instrução não permitida",
    "92": "Data de Desconto Inválida",
    "93": "Número do lote remessa inválido",
    "B2": "Valor Nominal do Boleto Conflitante",
    "B3": "Tipo de Pagamento Inválido",
    "B4": "Valor Máximo ou Percentual Máximo Inválido",
    "B5": "Valor Mínimo ou Percentual Mínimo Inválido",
    "C1": "Não foi realizada a contratação do produto SX Integra para operar com Cessão",
    "C2": "Operação de Cessão não Confirmada",
    "C3": "Operação de Cessão Rejeitada – Ver detalhes no relatório do SX Integra",
    "E1": "CNPJ Raiz do pagador não pode ser igual ao do beneficiário original",
    "E2": "CNPJ Raiz do pagador não pode ser igual ao do beneficiário final",
    "E3": "CNPJ Raiz do beneficiário final não pode ser igual ao CNPJ Raiz do beneficiário original para o convênio",
    "E4": "CPF do pagador não pode ser igual ao do beneficiário original",
    "E5": "CPF do pagador não pode ser igual ao do beneficiário final",
    "E6": "CPF do beneficiário final não pode ser igual ao CPF do beneficiário original para o convênio",
    "E7": "Registro não permitido – Beneficiário Final com restrição",
    "E8": "Código de Moeda Inválido",
    "E9": "Obrigatório informar o Beneficiário Final para o boleto",
    "P1": "Registrado com QR Code Pix",
    "P2": "Registrado sem QR Code Pix",
    "P3": "Chave PIX Inválida",
    "P4": "Chave PIX sem cadastro na DICT",
    "P5": "Chave PIX não é compatível com o CNPJ",
    "P6": "Identificador (TXID) em duplicidade",
    "P7": "Identificador (TXID) inválido ou não encontrado",
    "P8": "Alteração não permitida – QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "P9": "Cancelamento não permitido – QR Code concluído, removido pelo PSP ou removido pelo usuário recebedor",
    "Z1": "Quantidade de Pagamento Possíveis Inválido",
    "Z5": "Boleto com reserva, instrução não permitida",
    "Z6": "Segmento Inválido para o tipo de Carteira de Cobrança",
    "Z7": "Instrução exige segmento Y53",
    "Z8": "Instrução recusada - limite de alt.de vencto atingido p/ boletos em garantia",
    "Z9": "Instrução recusada pelo sistema de garantias",
    "B6": "Instrução recusada, convenio com garantia em conta Escrow",
    "A1": "Instrução recusada – Pix Automático",
}

LIQUIDACAO_CODES = {  # nota 40-C: origem da liquidação, com os movimentos 06, 17 e 93 (Segmento T, posições 209-218)
    "01": "Por saldo",
    "02": "Por conta",
    "03": "No próprio banco",
    "04": "Compensação eletrônica",
    "05": "Compensação convencional",
    "06": "Arquivo magnético",
    "07": "Após feriado local",
    "08": "Em cartório",
    "09": "Pagamento Parcial",
    "61": "Liquidação por pagamento PIX",
}

BAIXA_CODES = {  # nota 40-C: origem da baixa, com os movimentos 09 e 94 (Segmento T, posições 209-218)
    "09": "Comandada banco",
    "10": "Comandada cliente arquivo",
    "11": "Comandada cliente on-line",
    "12": "Decurso prazo - cliente",
    "13": "Decurso prazo - banco",
    "92": "Baixa por pagamento PIX",
    "93": "Pagamento do boleto recebido",
    "94": "Cancelamento do pagamento recebido",
}


def _validate_contiguous(fields, name, width=240):
    """Confere que a lista cobre 1..240 sem lacunas nem sobreposição e que cada campo tem título e descrição."""
    esperado = 1
    for campo in fields:
        assert len(campo) == 4, f"{name}: campo com {len(campo)} itens: {campo!r}"
        titulo, inicio, fim, descricao = campo
        assert titulo and descricao, f"{name}: campo sem título ou descrição em {inicio}"
        assert inicio == esperado, f"{name}: '{titulo}' começa em {inicio}, esperado {esperado}"
        assert fim >= inicio, f"{name}: '{titulo}' termina antes de começar ({inicio}-{fim})"
        esperado = fim + 1
    assert esperado - 1 == width, f"{name}: termina em {esperado - 1}, esperado {width}"



if __name__ == "__main__":
    listas = [(n, v) for n, v in sorted(globals().items()) if n.endswith("_FIELDS") and isinstance(v, list)]
    for nome, campos in listas:
        _validate_contiguous(campos, nome)
        print(f"{nome}: {len(campos)} campos, 1..240 OK")
    for chave, campos in SEGMENTOS.items():
        assert any("código de movimento" in c[0].lower() for c in campos), f"{chave}: sem Código de Movimento"
